//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.success {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuccRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.success.SuccRes", typeof(SuccRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El administrador {0} te ha revivido..
        /// </summary>
        public static string admin_revived {
            get {
                return ResourceManager.GetString("admin_revived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu duda ha sido enviada correctamente, espera a que te atienda un miembro del staff..
        /// </summary>
        public static string help_request_sent {
            get {
                return ResourceManager.GetString("help_request_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has terminado con este cliente..
        /// </summary>
        public static string hooker_client_satisfied {
            get {
                return ResourceManager.GetString("hooker_client_satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio de la prostituta ha terminado..
        /// </summary>
        public static string hooker_service_finished {
            get {
                return ResourceManager.GetString("hooker_service_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has vendido tu casa al estado por un valor de {0}$.
        /// </summary>
        public static string house_sold {
            get {
                return ResourceManager.GetString("house_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ha aceptado tu solicitud de entrevista..
        /// </summary>
        public static string interview_accepted {
            get {
                return ResourceManager.GetString("interview_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has aprobado el examen práctico..
        /// </summary>
        public static string license_drive_passed {
            get {
                return ResourceManager.GetString("license_drive_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has aprobado el examen teórico..
        /// </summary>
        public static string license_exam_passed {
            get {
                return ResourceManager.GetString("license_exam_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has logrado forzar la cerradura..
        /// </summary>
        public static string lockpicked {
            get {
                return ResourceManager.GetString("lockpicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ha conseguido un resultado positivo..
        /// </summary>
        public static string possitive_result {
            get {
                return ResourceManager.GetString("possitive_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El doctor {0} ha conseguido reanimarte..
        /// </summary>
        public static string target_reanimated {
            get {
                return ResourceManager.GetString("target_reanimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has conseguido arrancar el vehículo..
        /// </summary>
        public static string veh_hotwireed {
            get {
                return ResourceManager.GetString("veh_hotwireed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha bloqueado el vehículo..
        /// </summary>
        public static string veh_locked {
            get {
                return ResourceManager.GetString("veh_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha desbloqueado el vehículo..
        /// </summary>
        public static string veh_unlocked {
            get {
                return ResourceManager.GetString("veh_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has comprado tu vehículo..
        /// </summary>
        public static string vehicle_purchased {
            get {
                return ResourceManager.GetString("vehicle_purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has recibido {0}$ por desguazar tu vehículo..
        /// </summary>
        public static string vehicle_scrapyard {
            get {
                return ResourceManager.GetString("vehicle_scrapyard", resourceCulture);
            }
        }
    }
}
