//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.jobs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.jobs.JobRes", typeof(JobRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliary.
        /// </summary>
        public static string ems_1_f {
            get {
                return ResourceManager.GetString("ems_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliary.
        /// </summary>
        public static string ems_1_m {
            get {
                return ResourceManager.GetString("ems_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string ems_10_f {
            get {
                return ResourceManager.GetString("ems_10_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string ems_10_m {
            get {
                return ResourceManager.GetString("ems_10_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nurse.
        /// </summary>
        public static string ems_2_f {
            get {
                return ResourceManager.GetString("ems_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nurse.
        /// </summary>
        public static string ems_2_m {
            get {
                return ResourceManager.GetString("ems_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjunct surgeon.
        /// </summary>
        public static string ems_3_f {
            get {
                return ResourceManager.GetString("ems_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjunct surgeon.
        /// </summary>
        public static string ems_3_m {
            get {
                return ResourceManager.GetString("ems_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paramedic.
        /// </summary>
        public static string ems_4_f {
            get {
                return ResourceManager.GetString("ems_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paramedic.
        /// </summary>
        public static string ems_4_m {
            get {
                return ResourceManager.GetString("ems_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First class surgeon.
        /// </summary>
        public static string ems_5_f {
            get {
                return ResourceManager.GetString("ems_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First class surgeon.
        /// </summary>
        public static string ems_5_m {
            get {
                return ResourceManager.GetString("ems_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medic.
        /// </summary>
        public static string ems_6_f {
            get {
                return ResourceManager.GetString("ems_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medic.
        /// </summary>
        public static string ems_6_m {
            get {
                return ResourceManager.GetString("ems_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chief surgeon.
        /// </summary>
        public static string ems_7_f {
            get {
                return ResourceManager.GetString("ems_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chief surgeon.
        /// </summary>
        public static string ems_7_m {
            get {
                return ResourceManager.GetString("ems_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Head of emergency.
        /// </summary>
        public static string ems_8_f {
            get {
                return ResourceManager.GetString("ems_8_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Head of emergency.
        /// </summary>
        public static string ems_8_m {
            get {
                return ResourceManager.GetString("ems_8_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice principal.
        /// </summary>
        public static string ems_9_f {
            get {
                return ResourceManager.GetString("ems_9_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice principal.
        /// </summary>
        public static string ems_9_m {
            get {
                return ResourceManager.GetString("ems_9_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery woman.
        /// </summary>
        public static string fastfood_f {
            get {
                return ResourceManager.GetString("fastfood_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delivery man.
        /// </summary>
        public static string fastfood_m {
            get {
                return ResourceManager.GetString("fastfood_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garbage woman.
        /// </summary>
        public static string gargage_f {
            get {
                return ResourceManager.GetString("gargage_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garbage man.
        /// </summary>
        public static string gargage_m {
            get {
                return ResourceManager.GetString("gargage_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prostitute.
        /// </summary>
        public static string hooker_f {
            get {
                return ResourceManager.GetString("hooker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gigolo.
        /// </summary>
        public static string hooker_m {
            get {
                return ResourceManager.GetString("hooker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snitch.
        /// </summary>
        public static string lspd_0_f {
            get {
                return ResourceManager.GetString("lspd_0_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snitch.
        /// </summary>
        public static string lspd_0_m {
            get {
                return ResourceManager.GetString("lspd_0_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadet.
        /// </summary>
        public static string lspd_1_f {
            get {
                return ResourceManager.GetString("lspd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadet.
        /// </summary>
        public static string lspd_1_m {
            get {
                return ResourceManager.GetString("lspd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Officer.
        /// </summary>
        public static string lspd_2_f {
            get {
                return ResourceManager.GetString("lspd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Officer.
        /// </summary>
        public static string lspd_2_m {
            get {
                return ResourceManager.GetString("lspd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sergeant.
        /// </summary>
        public static string lspd_3_f {
            get {
                return ResourceManager.GetString("lspd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sergeant.
        /// </summary>
        public static string lspd_3_m {
            get {
                return ResourceManager.GetString("lspd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lieutenant.
        /// </summary>
        public static string lspd_4_f {
            get {
                return ResourceManager.GetString("lspd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lieutenant.
        /// </summary>
        public static string lspd_4_m {
            get {
                return ResourceManager.GetString("lspd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Captain.
        /// </summary>
        public static string lspd_5_f {
            get {
                return ResourceManager.GetString("lspd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Captain.
        /// </summary>
        public static string lspd_5_m {
            get {
                return ResourceManager.GetString("lspd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commissar.
        /// </summary>
        public static string lspd_6_f {
            get {
                return ResourceManager.GetString("lspd_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commissar.
        /// </summary>
        public static string lspd_6_m {
            get {
                return ResourceManager.GetString("lspd_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal Affairs.
        /// </summary>
        public static string lspd_7_f {
            get {
                return ResourceManager.GetString("lspd_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal Affairs.
        /// </summary>
        public static string lspd_7_m {
            get {
                return ResourceManager.GetString("lspd_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver.
        /// </summary>
        public static string lstd_1_f {
            get {
                return ResourceManager.GetString("lstd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Driver.
        /// </summary>
        public static string lstd_1_m {
            get {
                return ResourceManager.GetString("lstd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veteran.
        /// </summary>
        public static string lstd_2_f {
            get {
                return ResourceManager.GetString("lstd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veteran.
        /// </summary>
        public static string lstd_2_m {
            get {
                return ResourceManager.GetString("lstd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        public static string lstd_3_f {
            get {
                return ResourceManager.GetString("lstd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        public static string lstd_3_m {
            get {
                return ResourceManager.GetString("lstd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice president.
        /// </summary>
        public static string lstd_4_f {
            get {
                return ResourceManager.GetString("lstd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice president.
        /// </summary>
        public static string lstd_4_m {
            get {
                return ResourceManager.GetString("lstd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a President.
        /// </summary>
        public static string lstd_5_f {
            get {
                return ResourceManager.GetString("lstd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a President.
        /// </summary>
        public static string lstd_5_m {
            get {
                return ResourceManager.GetString("lstd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanic.
        /// </summary>
        public static string mechanic_f {
            get {
                return ResourceManager.GetString("mechanic_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mechanic.
        /// </summary>
        public static string mechanic_m {
            get {
                return ResourceManager.GetString("mechanic_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scholar.
        /// </summary>
        public static string news_1_f {
            get {
                return ResourceManager.GetString("news_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scholar.
        /// </summary>
        public static string news_1_m {
            get {
                return ResourceManager.GetString("news_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Journalist.
        /// </summary>
        public static string news_2_f {
            get {
                return ResourceManager.GetString("news_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Journalist.
        /// </summary>
        public static string news_2_m {
            get {
                return ResourceManager.GetString("news_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broadcaster.
        /// </summary>
        public static string news_3_f {
            get {
                return ResourceManager.GetString("news_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broadcaster.
        /// </summary>
        public static string news_3_m {
            get {
                return ResourceManager.GetString("news_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice principal.
        /// </summary>
        public static string news_4_f {
            get {
                return ResourceManager.GetString("news_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vice principal.
        /// </summary>
        public static string news_4_m {
            get {
                return ResourceManager.GetString("news_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string news_5_f {
            get {
                return ResourceManager.GetString("news_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string news_5_m {
            get {
                return ResourceManager.GetString("news_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Civilian.
        /// </summary>
        public static string none_f {
            get {
                return ResourceManager.GetString("none_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Civilian.
        /// </summary>
        public static string none_m {
            get {
                return ResourceManager.GetString("none_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thief.
        /// </summary>
        public static string thief_f {
            get {
                return ResourceManager.GetString("thief_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thief.
        /// </summary>
        public static string thief_m {
            get {
                return ResourceManager.GetString("thief_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scholar.
        /// </summary>
        public static string town_1_f {
            get {
                return ResourceManager.GetString("town_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scholar.
        /// </summary>
        public static string town_1_m {
            get {
                return ResourceManager.GetString("town_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official.
        /// </summary>
        public static string town_2_f {
            get {
                return ResourceManager.GetString("town_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Official.
        /// </summary>
        public static string town_2_m {
            get {
                return ResourceManager.GetString("town_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Head of department.
        /// </summary>
        public static string town_3_f {
            get {
                return ResourceManager.GetString("town_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Head of department.
        /// </summary>
        public static string town_3_m {
            get {
                return ResourceManager.GetString("town_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor.
        /// </summary>
        public static string town_4_f {
            get {
                return ResourceManager.GetString("town_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor.
        /// </summary>
        public static string town_4_m {
            get {
                return ResourceManager.GetString("town_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trucker.
        /// </summary>
        public static string trucker_f {
            get {
                return ResourceManager.GetString("trucker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trucker.
        /// </summary>
        public static string trucker_m {
            get {
                return ResourceManager.GetString("trucker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unemployed.
        /// </summary>
        public static string unemployed_f {
            get {
                return ResourceManager.GetString("unemployed_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unemployed.
        /// </summary>
        public static string unemployed_m {
            get {
                return ResourceManager.GetString("unemployed_m", resourceCulture);
            }
        }
    }
}
