//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.description {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.description.DescRes", typeof(DescRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repartidor - Necesitamos repartidores de comida rápida en moto. Es simple, entrega los pedidos a tiempo y recibirás tu paga..
        /// </summary>
        public static string job_fastfoot {
            get {
                return ResourceManager.GetString("job_fastfoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basurero - Los Santos necesita gente que mantenga limpia la ciudad. Trabajo por parejas, uno conduce y el otro recoge y cada uno recibe su sueldo..
        /// </summary>
        public static string job_garbage {
            get {
                return ResourceManager.GetString("job_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prostitución - Gana dinero vendiendo tu cuerpo, es tan sencillo como eso.Tú eliges tus clientes y tus precios..
        /// </summary>
        public static string job_hooker {
            get {
                return ResourceManager.GetString("job_hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mecánico - En LS Custom necesitamos empleados que sepan reparar chapa, cambiar ruedas, arreglar fallos de motor e instalar modificaciones..
        /// </summary>
        public static string job_mechanic {
            get {
                return ResourceManager.GetString("job_mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ladrón - Si trabajar es demasiado aburrido para ti quizás te atraiga más la idea de robar a quienes trabajan. Siempre podrás vender lo robado..
        /// </summary>
        public static string job_thief {
            get {
                return ResourceManager.GetString("job_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transportista - Si lo tuyo es pasar largas temporadas en solitario con tu camión, estás de enhorabuena. Ponte a repartir toda la mercancia a lo largo y ancho de Los Santos..
        /// </summary>
        public static string job_trucker {
            get {
                return ResourceManager.GetString("job_trucker", resourceCulture);
            }
        }
    }
}
