//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.jobs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.jobs.JobRes", typeof(JobRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar.
        /// </summary>
        public static string ems_1_f {
            get {
                return ResourceManager.GetString("ems_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auxiliar.
        /// </summary>
        public static string ems_1_m {
            get {
                return ResourceManager.GetString("ems_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directora.
        /// </summary>
        public static string ems_10_f {
            get {
                return ResourceManager.GetString("ems_10_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director.
        /// </summary>
        public static string ems_10_m {
            get {
                return ResourceManager.GetString("ems_10_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enfermera.
        /// </summary>
        public static string ems_2_f {
            get {
                return ResourceManager.GetString("ems_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enfermero.
        /// </summary>
        public static string ems_2_m {
            get {
                return ResourceManager.GetString("ems_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujana adjunta.
        /// </summary>
        public static string ems_3_f {
            get {
                return ResourceManager.GetString("ems_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujano adjunto.
        /// </summary>
        public static string ems_3_m {
            get {
                return ResourceManager.GetString("ems_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paramédico.
        /// </summary>
        public static string ems_4_f {
            get {
                return ResourceManager.GetString("ems_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paramédico.
        /// </summary>
        public static string ems_4_m {
            get {
                return ResourceManager.GetString("ems_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujana de primera.
        /// </summary>
        public static string ems_5_f {
            get {
                return ResourceManager.GetString("ems_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujano de primera.
        /// </summary>
        public static string ems_5_m {
            get {
                return ResourceManager.GetString("ems_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Médico.
        /// </summary>
        public static string ems_6_f {
            get {
                return ResourceManager.GetString("ems_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Médico.
        /// </summary>
        public static string ems_6_m {
            get {
                return ResourceManager.GetString("ems_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujana jefa.
        /// </summary>
        public static string ems_7_f {
            get {
                return ResourceManager.GetString("ems_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cirujano jefe.
        /// </summary>
        public static string ems_7_m {
            get {
                return ResourceManager.GetString("ems_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefa de urgencias.
        /// </summary>
        public static string ems_8_f {
            get {
                return ResourceManager.GetString("ems_8_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefe de urgencias.
        /// </summary>
        public static string ems_8_m {
            get {
                return ResourceManager.GetString("ems_8_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdirectora.
        /// </summary>
        public static string ems_9_f {
            get {
                return ResourceManager.GetString("ems_9_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdirector.
        /// </summary>
        public static string ems_9_m {
            get {
                return ResourceManager.GetString("ems_9_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repartidora.
        /// </summary>
        public static string fastfood_f {
            get {
                return ResourceManager.GetString("fastfood_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repartidor.
        /// </summary>
        public static string fastfood_m {
            get {
                return ResourceManager.GetString("fastfood_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basurera.
        /// </summary>
        public static string gargage_f {
            get {
                return ResourceManager.GetString("gargage_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Basurero.
        /// </summary>
        public static string gargage_m {
            get {
                return ResourceManager.GetString("gargage_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prostituta.
        /// </summary>
        public static string hooker_f {
            get {
                return ResourceManager.GetString("hooker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gigoló.
        /// </summary>
        public static string hooker_m {
            get {
                return ResourceManager.GetString("hooker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soplona.
        /// </summary>
        public static string lspd_0_f {
            get {
                return ResourceManager.GetString("lspd_0_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soplón.
        /// </summary>
        public static string lspd_0_m {
            get {
                return ResourceManager.GetString("lspd_0_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadete.
        /// </summary>
        public static string lspd_1_f {
            get {
                return ResourceManager.GetString("lspd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cadete.
        /// </summary>
        public static string lspd_1_m {
            get {
                return ResourceManager.GetString("lspd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oficial.
        /// </summary>
        public static string lspd_2_f {
            get {
                return ResourceManager.GetString("lspd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oficial.
        /// </summary>
        public static string lspd_2_m {
            get {
                return ResourceManager.GetString("lspd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sargento.
        /// </summary>
        public static string lspd_3_f {
            get {
                return ResourceManager.GetString("lspd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sargento.
        /// </summary>
        public static string lspd_3_m {
            get {
                return ResourceManager.GetString("lspd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teniente.
        /// </summary>
        public static string lspd_4_f {
            get {
                return ResourceManager.GetString("lspd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teniente.
        /// </summary>
        public static string lspd_4_m {
            get {
                return ResourceManager.GetString("lspd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capitán.
        /// </summary>
        public static string lspd_5_f {
            get {
                return ResourceManager.GetString("lspd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capitán.
        /// </summary>
        public static string lspd_5_m {
            get {
                return ResourceManager.GetString("lspd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comisaria.
        /// </summary>
        public static string lspd_6_f {
            get {
                return ResourceManager.GetString("lspd_6_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comisario.
        /// </summary>
        public static string lspd_6_m {
            get {
                return ResourceManager.GetString("lspd_6_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asuntos Internos.
        /// </summary>
        public static string lspd_7_f {
            get {
                return ResourceManager.GetString("lspd_7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asuntos Internos.
        /// </summary>
        public static string lspd_7_m {
            get {
                return ResourceManager.GetString("lspd_7_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductora.
        /// </summary>
        public static string lstd_1_f {
            get {
                return ResourceManager.GetString("lstd_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductor.
        /// </summary>
        public static string lstd_1_m {
            get {
                return ResourceManager.GetString("lstd_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterana.
        /// </summary>
        public static string lstd_2_f {
            get {
                return ResourceManager.GetString("lstd_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterano.
        /// </summary>
        public static string lstd_2_m {
            get {
                return ResourceManager.GetString("lstd_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerente.
        /// </summary>
        public static string lstd_3_f {
            get {
                return ResourceManager.GetString("lstd_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerente.
        /// </summary>
        public static string lstd_3_m {
            get {
                return ResourceManager.GetString("lstd_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vicepresidenta.
        /// </summary>
        public static string lstd_4_f {
            get {
                return ResourceManager.GetString("lstd_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vicepresidente.
        /// </summary>
        public static string lstd_4_m {
            get {
                return ResourceManager.GetString("lstd_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presidenta.
        /// </summary>
        public static string lstd_5_f {
            get {
                return ResourceManager.GetString("lstd_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presidente.
        /// </summary>
        public static string lstd_5_m {
            get {
                return ResourceManager.GetString("lstd_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mecánica.
        /// </summary>
        public static string mechanic_f {
            get {
                return ResourceManager.GetString("mechanic_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mecánico.
        /// </summary>
        public static string mechanic_m {
            get {
                return ResourceManager.GetString("mechanic_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Becaria.
        /// </summary>
        public static string news_1_f {
            get {
                return ResourceManager.GetString("news_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Becario.
        /// </summary>
        public static string news_1_m {
            get {
                return ResourceManager.GetString("news_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodista.
        /// </summary>
        public static string news_2_f {
            get {
                return ResourceManager.GetString("news_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodista.
        /// </summary>
        public static string news_2_m {
            get {
                return ResourceManager.GetString("news_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locutora.
        /// </summary>
        public static string news_3_f {
            get {
                return ResourceManager.GetString("news_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locutor.
        /// </summary>
        public static string news_3_m {
            get {
                return ResourceManager.GetString("news_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdirectora.
        /// </summary>
        public static string news_4_f {
            get {
                return ResourceManager.GetString("news_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subdirector.
        /// </summary>
        public static string news_4_m {
            get {
                return ResourceManager.GetString("news_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directora.
        /// </summary>
        public static string news_5_f {
            get {
                return ResourceManager.GetString("news_5_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director.
        /// </summary>
        public static string news_5_m {
            get {
                return ResourceManager.GetString("news_5_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Civil.
        /// </summary>
        public static string none_f {
            get {
                return ResourceManager.GetString("none_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Civil.
        /// </summary>
        public static string none_m {
            get {
                return ResourceManager.GetString("none_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ladrona.
        /// </summary>
        public static string thief_f {
            get {
                return ResourceManager.GetString("thief_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ladrón.
        /// </summary>
        public static string thief_m {
            get {
                return ResourceManager.GetString("thief_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Becaria.
        /// </summary>
        public static string town_1_f {
            get {
                return ResourceManager.GetString("town_1_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Becario.
        /// </summary>
        public static string town_1_m {
            get {
                return ResourceManager.GetString("town_1_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionaria.
        /// </summary>
        public static string town_2_f {
            get {
                return ResourceManager.GetString("town_2_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionario.
        /// </summary>
        public static string town_2_m {
            get {
                return ResourceManager.GetString("town_2_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefa de departamento.
        /// </summary>
        public static string town_3_f {
            get {
                return ResourceManager.GetString("town_3_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jefe de departamento.
        /// </summary>
        public static string town_3_m {
            get {
                return ResourceManager.GetString("town_3_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcaldesa.
        /// </summary>
        public static string town_4_f {
            get {
                return ResourceManager.GetString("town_4_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alcalde.
        /// </summary>
        public static string town_4_m {
            get {
                return ResourceManager.GetString("town_4_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camionera.
        /// </summary>
        public static string trucker_f {
            get {
                return ResourceManager.GetString("trucker_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camionero.
        /// </summary>
        public static string trucker_m {
            get {
                return ResourceManager.GetString("trucker_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desempleada.
        /// </summary>
        public static string unemployed_f {
            get {
                return ResourceManager.GetString("unemployed_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desempleado.
        /// </summary>
        public static string unemployed_m {
            get {
                return ResourceManager.GetString("unemployed_m", resourceCulture);
            }
        }
    }
}
