//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.general {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.general.GenRes", typeof(GenRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [AVISO ADMINISTRATIVO] .
        /// </summary>
        public static string admin_notice {
            get {
                return ResourceManager.GetString("admin_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad: .
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [ANUNCIO] .
        /// </summary>
        public static string announcement {
            get {
                return ResourceManager.GetString("announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado: atendido por .
        /// </summary>
        public static string attended_by {
            get {
                return ResourceManager.GetString("attended_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco: .
        /// </summary>
        public static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intereses bancarios: .
        /// </summary>
        public static string bank_interest {
            get {
                return ResourceManager.GetString("bank_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depósito.
        /// </summary>
        public static string bank_op_deposit {
            get {
                return ResourceManager.GetString("bank_op_deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia.
        /// </summary>
        public static string bank_op_transfer {
            get {
                return ResourceManager.GetString("bank_op_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retiro.
        /// </summary>
        public static string bank_op_withdraw {
            get {
                return ResourceManager.GetString("bank_op_withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concesionario de barcos.
        /// </summary>
        public static string boat_dealer {
            get {
                return ResourceManager.GetString("boat_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negocio.
        /// </summary>
        public static string business {
            get {
                return ResourceManager.GetString("business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concesionario de coches.
        /// </summary>
        public static string car_dealer {
            get {
                return ResourceManager.GetString("car_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el comando para ver la lista de vehículos.
        /// </summary>
        public static string catalog_help {
            get {
                return ResourceManager.GetString("catalog_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pulsa F para cambiar de personaje.
        /// </summary>
        public static string character_help {
            get {
                return ResourceManager.GetString("character_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  por teléfono: .
        /// </summary>
        public static string chat_phone {
            get {
                return ResourceManager.GetString("chat_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  por radio: .
        /// </summary>
        public static string chat_radio {
            get {
                return ResourceManager.GetString("chat_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  dice: .
        /// </summary>
        public static string chat_say {
            get {
                return ResourceManager.GetString("chat_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  susurra: .
        /// </summary>
        public static string chat_whisper {
            get {
                return ResourceManager.GetString("chat_whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  grita: ¡.
        /// </summary>
        public static string chat_yell {
            get {
                return ResourceManager.GetString("chat_yell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoescuela.
        /// </summary>
        public static string driving_school {
            get {
                return ResourceManager.GetString("driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergencias.
        /// </summary>
        public static string emergency_faction {
            get {
                return ResourceManager.GetString("emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el comando para acceder al equipo de policía.
        /// </summary>
        public static string equipment_help {
            get {
                return ResourceManager.GetString("equipment_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de expiración: .
        /// </summary>
        public static string expiry {
            get {
                return ResourceManager.GetString("expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos extra: .
        /// </summary>
        public static string extra_income {
            get {
                return ResourceManager.GetString("extra_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facción: .
        /// </summary>
        public static string faction {
            get {
                return ResourceManager.GetString("faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMS.
        /// </summary>
        public static string faction_ems {
            get {
                return ResourceManager.GetString("faction_ems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LSPD.
        /// </summary>
        public static string faction_lspd {
            get {
                return ResourceManager.GetString("faction_lspd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string faction_news {
            get {
                return ResourceManager.GetString("faction_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuntamiento.
        /// </summary>
        public static string faction_townhall {
            get {
                return ResourceManager.GetString("faction_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de transportes.
        /// </summary>
        public static string faction_transport {
            get {
                return ResourceManager.GetString("faction_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo de repartidor.
        /// </summary>
        public static string fastfood_job {
            get {
                return ResourceManager.GetString("fastfood_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago de multas.
        /// </summary>
        public static string fines_payment {
            get {
                return ResourceManager.GetString("fines_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garaje.
        /// </summary>
        public static string garage {
            get {
                return ResourceManager.GetString("garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo de basurero.
        /// </summary>
        public static string garbage_job {
            get {
                return ResourceManager.GetString("garbage_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado .
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utiliza el comando ~b~/ayuda ~w~siempre que quieras para obtener información general..
        /// </summary>
        public static string help_hint {
            get {
                return ResourceManager.GetString("help_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de prostitución.
        /// </summary>
        public static string hooker {
            get {
                return ResourceManager.GetString("hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospital.
        /// </summary>
        public static string hospital {
            get {
                return ResourceManager.GetString("hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa.
        /// </summary>
        public static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a __________Información de la casa con ID {0}:__________.
        /// </summary>
        public static string house_check_title {
            get {
                return ResourceManager.GetString("house_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta de casa.
        /// </summary>
        public static string house_sale {
            get {
                return ResourceManager.GetString("house_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impuestos de la vivienda .
        /// </summary>
        public static string house_taxes_from {
            get {
                return ResourceManager.GetString("house_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casas: .
        /// </summary>
        public static string houses {
            get {
                return ResourceManager.GetString("houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación.
        /// </summary>
        public static string identification {
            get {
                return ResourceManager.GetString("identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locutor .
        /// </summary>
        public static string interviewer {
            get {
                return ResourceManager.GetString("interviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IPL: .
        /// </summary>
        public static string ipl {
            get {
                return ResourceManager.GetString("ipl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo: .
        /// </summary>
        public static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el comando para obtener más información del empleo.
        /// </summary>
        public static string job_help {
            get {
                return ResourceManager.GetString("job_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículos cedidos: .
        /// </summary>
        public static string lent_vehicles {
            get {
                return ResourceManager.GetString("lent_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajo de mecánico.
        /// </summary>
        public static string mechanic_job {
            get {
                return ResourceManager.GetString("mechanic_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro médico.
        /// </summary>
        public static string medical_insurance {
            get {
                return ResourceManager.GetString("medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros conectados:.
        /// </summary>
        public static string members_online {
            get {
                return ResourceManager.GetString("members_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero: .
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concesionario de motos.
        /// </summary>
        public static string motorcycle_dealer {
            get {
                return ResourceManager.GetString("motorcycle_dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre: .
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anuncio Weazel News.
        /// </summary>
        public static string news_announce {
            get {
                return ResourceManager.GetString("news_announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string news_faction {
            get {
                return ResourceManager.GetString("news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premio Weazel News.
        /// </summary>
        public static string news_prize {
            get {
                return ResourceManager.GetString("news_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin facción.
        /// </summary>
        public static string no_faction {
            get {
                return ResourceManager.GetString("no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin rango.
        /// </summary>
        public static string no_rank {
            get {
                return ResourceManager.GetString("no_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ningún aviso pendiente..
        /// </summary>
        public static string not_faction_warning {
            get {
                return ResourceManager.GetString("not_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vehículos propios: .
        /// </summary>
        public static string owned_vehicles {
            get {
                return ResourceManager.GetString("owned_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propietario: .
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda de empeños.
        /// </summary>
        public static string pawn_shop {
            get {
                return ResourceManager.GetString("pawn_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago entre jugadores.
        /// </summary>
        public static string payment_players {
            get {
                return ResourceManager.GetString("payment_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Teléfono] .
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lugar: .
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo jugado: .
        /// </summary>
        public static string played_time {
            get {
                return ResourceManager.GetString("played_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje privado de .
        /// </summary>
        public static string pm_from {
            get {
                return ResourceManager.GetString("pm_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje privado a .
        /// </summary>
        public static string pm_to {
            get {
                return ResourceManager.GetString("pm_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depósito policial.
        /// </summary>
        public static string police_depot {
            get {
                return ResourceManager.GetString("police_depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Policía.
        /// </summary>
        public static string police_faction {
            get {
                return ResourceManager.GetString("police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comisaría.
        /// </summary>
        public static string police_station {
            get {
                return ResourceManager.GetString("police_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio: .
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking público.
        /// </summary>
        public static string public_parking {
            get {
                return ResourceManager.GetString("public_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Radio] .
        /// </summary>
        public static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango: .
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de avisos:.
        /// </summary>
        public static string reports_header {
            get {
                return ResourceManager.GetString("reports_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos de rol: .
        /// </summary>
        public static string role_points {
            get {
                return ResourceManager.GetString("role_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te ha asignado la ruta este..
        /// </summary>
        public static string route_east {
            get {
                return ResourceManager.GetString("route_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te ha asignado la ruta norte..
        /// </summary>
        public static string route_north {
            get {
                return ResourceManager.GetString("route_north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te ha asignado la ruta sur..
        /// </summary>
        public static string route_south {
            get {
                return ResourceManager.GetString("route_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se te ha asignado la ruta oeste..
        /// </summary>
        public static string route_west {
            get {
                return ResourceManager.GetString("route_west", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sueldo: .
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desguace.
        /// </summary>
        public static string scrapyard {
            get {
                return ResourceManager.GetString("scrapyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo: .
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string sex_female {
            get {
                return ResourceManager.GetString("sex_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string sex_male {
            get {
                return ResourceManager.GetString("sex_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMS de .
        /// </summary>
        public static string sms_from {
            get {
                return ResourceManager.GetString("sms_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: Ocupada.
        /// </summary>
        public static string state_occupied {
            get {
                return ResourceManager.GetString("state_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: En alquiler.
        /// </summary>
        public static string state_rent {
            get {
                return ResourceManager.GetString("state_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: En venta.
        /// </summary>
        public static string state_sale {
            get {
                return ResourceManager.GetString("state_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado: .
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia de taxis.
        /// </summary>
        public static string taxi_license {
            get {
                return ResourceManager.GetString("taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utiliza el comando ~b~/duda ~w~para solicitar ayuda de algún miembro del staff..
        /// </summary>
        public static string ticket_hint {
            get {
                return ResourceManager.GetString("ticket_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora: .
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuntamiento.
        /// </summary>
        public static string townhall {
            get {
                return ResourceManager.GetString("townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuntamiento.
        /// </summary>
        public static string townhall_faction {
            get {
                return ResourceManager.GetString("townhall_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe el comando para ver los trámites disponibles.
        /// </summary>
        public static string townhall_help {
            get {
                return ResourceManager.GetString("townhall_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de transportes.
        /// </summary>
        public static string transport_faction {
            get {
                return ResourceManager.GetString("transport_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a estado: sin atender.
        /// </summary>
        public static string unattended {
            get {
                return ResourceManager.GetString("unattended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin trabajo.
        /// </summary>
        public static string unemployed {
            get {
                return ResourceManager.GetString("unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _________Información del vehículo con ID {0}_________.
        /// </summary>
        public static string vehicle_check_title {
            get {
                return ResourceManager.GetString("vehicle_check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo: .
        /// </summary>
        public static string vehicle_model {
            get {
                return ResourceManager.GetString("vehicle_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matrícula: .
        /// </summary>
        public static string vehicle_plate {
            get {
                return ResourceManager.GetString("vehicle_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta de vehículo.
        /// </summary>
        public static string vehicle_sale {
            get {
                return ResourceManager.GetString("vehicle_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impuestos de .
        /// </summary>
        public static string vehicle_taxes_from {
            get {
                return ResourceManager.GetString("vehicle_taxes_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a caja de armas.
        /// </summary>
        public static string weapon_crate {
            get {
                return ResourceManager.GetString("weapon_crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weazel News.
        /// </summary>
        public static string weazel_news {
            get {
                return ResourceManager.GetString("weazel_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utiliza el comando ~b~/bienvenida ~w~para saber como puedes empezar tu vida en Los Santos..
        /// </summary>
        public static string welcome_hint {
            get {
                return ResourceManager.GetString("welcome_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a WiredPlayers, {0}..
        /// </summary>
        public static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  años.
        /// </summary>
        public static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
    }
}
