//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.items {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.items.ItemRes", typeof(ItemRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Advanced rifle&quot;.
        /// </summary>
        public static string advanced_rifle {
            get {
                return ResourceManager.GetString("advanced_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;AP Pistol&quot;.
        /// </summary>
        public static string ap_pistol {
            get {
                return ResourceManager.GetString("ap_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Assault rifle&quot;.
        /// </summary>
        public static string assault_rifle {
            get {
                return ResourceManager.GetString("assault_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Assault shotgun&quot;.
        /// </summary>
        public static string assault_shotgun {
            get {
                return ResourceManager.GetString("assault_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Assault SMG&quot;.
        /// </summary>
        public static string assault_smg {
            get {
                return ResourceManager.GetString("assault_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Bait&quot;.
        /// </summary>
        public static string bait {
            get {
                return ResourceManager.GetString("bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Bat&quot;.
        /// </summary>
        public static string bat {
            get {
                return ResourceManager.GetString("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Beer bottle&quot;.
        /// </summary>
        public static string beer_bottle {
            get {
                return ResourceManager.GetString("beer_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Beer pack&quot;.
        /// </summary>
        public static string beer_pack {
            get {
                return ResourceManager.GetString("beer_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Bullpup rifle&quot;.
        /// </summary>
        public static string bullpup_rifle {
            get {
                return ResourceManager.GetString("bullpup_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Bullpup shotgun&quot;.
        /// </summary>
        public static string bullpup_shotgun {
            get {
                return ResourceManager.GetString("bullpup_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Burger&quot;.
        /// </summary>
        public static string burger {
            get {
                return ResourceManager.GetString("burger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Camera&quot;.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Candies&quot;.
        /// </summary>
        public static string candy {
            get {
                return ResourceManager.GetString("candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Carbine&quot;.
        /// </summary>
        public static string carbine_rifle {
            get {
                return ResourceManager.GetString("carbine_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Cava bottle&quot;.
        /// </summary>
        public static string cava_bottle {
            get {
                return ResourceManager.GetString("cava_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;RedWood cigarettes&quot;.
        /// </summary>
        public static string cigarettes {
            get {
                return ResourceManager.GetString("cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Coffee&quot;.
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;FunCola&quot;.
        /// </summary>
        public static string cola {
            get {
                return ResourceManager.GetString("cola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Combat PDW&quot;.
        /// </summary>
        public static string combat_pdw {
            get {
                return ResourceManager.GetString("combat_pdw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Compact rifle&quot;.
        /// </summary>
        public static string compact_rifle {
            get {
                return ResourceManager.GetString("compact_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Crowbar&quot;.
        /// </summary>
        public static string crowbar {
            get {
                return ResourceManager.GetString("crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Double barrel shotgun&quot;.
        /// </summary>
        public static string double_barrel_shotgun {
            get {
                return ResourceManager.GetString("double_barrel_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Energy drink&quot;.
        /// </summary>
        public static string energy_drink {
            get {
                return ResourceManager.GetString("energy_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Fish&quot;.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Fishing rod&quot;.
        /// </summary>
        public static string fishing_rod {
            get {
                return ResourceManager.GetString("fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Flashlight&quot;.
        /// </summary>
        public static string flashlight {
            get {
                return ResourceManager.GetString("flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Golf club&quot;.
        /// </summary>
        public static string golf_club {
            get {
                return ResourceManager.GetString("golf_club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Hammer&quot;.
        /// </summary>
        public static string hammer {
            get {
                return ResourceManager.GetString("hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Hatchet&quot;.
        /// </summary>
        public static string hatchet {
            get {
                return ResourceManager.GetString("hatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Heavy pistol&quot;.
        /// </summary>
        public static string heavy_pistol {
            get {
                return ResourceManager.GetString("heavy_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Heavy shotgun&quot;.
        /// </summary>
        public static string heavy_shotgun {
            get {
                return ResourceManager.GetString("heavy_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Heavy sniper rifle&quot;.
        /// </summary>
        public static string heavy_sniper {
            get {
                return ResourceManager.GetString("heavy_sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Hot dog&quot;.
        /// </summary>
        public static string hotdog {
            get {
                return ResourceManager.GetString("hotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Jerrycan&quot;.
        /// </summary>
        public static string jerrycan {
            get {
                return ResourceManager.GetString("jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Juice&quot;.
        /// </summary>
        public static string juice {
            get {
                return ResourceManager.GetString("juice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Knife&quot;.
        /// </summary>
        public static string knife {
            get {
                return ResourceManager.GetString("knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Knuckle duster&quot;.
        /// </summary>
        public static string knucle_duster {
            get {
                return ResourceManager.GetString("knucle_duster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Machine pistol&quot;.
        /// </summary>
        public static string machine_pistol {
            get {
                return ResourceManager.GetString("machine_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Marksman rifle&quot;.
        /// </summary>
        public static string marksman_rifle {
            get {
                return ResourceManager.GetString("marksman_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Micro SMG&quot;.
        /// </summary>
        public static string micro_smg {
            get {
                return ResourceManager.GetString("micro_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Pistol&quot;.
        /// </summary>
        public static string pistol {
            get {
                return ResourceManager.GetString("pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Pistol 50&quot;.
        /// </summary>
        public static string pistol_50 {
            get {
                return ResourceManager.GetString("pistol_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Pistol ammunition&quot;.
        /// </summary>
        public static string pistol_ammo {
            get {
                return ResourceManager.GetString("pistol_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Products&quot;.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Pump shotgun&quot;.
        /// </summary>
        public static string pump_shotgun {
            get {
                return ResourceManager.GetString("pump_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Revolver&quot;.
        /// </summary>
        public static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Assault rifle ammunition&quot;.
        /// </summary>
        public static string rifle_ammo {
            get {
                return ResourceManager.GetString("rifle_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Sandwich&quot;.
        /// </summary>
        public static string sandwich {
            get {
                return ResourceManager.GetString("sandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Sawn-off shotgun&quot;.
        /// </summary>
        public static string sawn_off_shotgun {
            get {
                return ResourceManager.GetString("sawn_off_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Shotgun ammunition&quot;.
        /// </summary>
        public static string shotgun_ammo {
            get {
                return ResourceManager.GetString("shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Smartphone&quot;.
        /// </summary>
        public static string smartphone {
            get {
                return ResourceManager.GetString("smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;SMG&quot;.
        /// </summary>
        public static string smg {
            get {
                return ResourceManager.GetString("smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Machine gun ammunition&quot;.
        /// </summary>
        public static string smg_ammo {
            get {
                return ResourceManager.GetString("smg_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Sniper rifle ammunition&quot;.
        /// </summary>
        public static string sniper_ammo {
            get {
                return ResourceManager.GetString("sniper_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Sniper rifle&quot;.
        /// </summary>
        public static string sniper_rifle {
            get {
                return ResourceManager.GetString("sniper_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Special carbine&quot;.
        /// </summary>
        public static string special_carbine {
            get {
                return ResourceManager.GetString("special_carbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Stolen items&quot;.
        /// </summary>
        public static string stolen_items {
            get {
                return ResourceManager.GetString("stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Switchblade&quot;.
        /// </summary>
        public static string switchblade {
            get {
                return ResourceManager.GetString("switchblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Walkie-Talkie&quot;.
        /// </summary>
        public static string walkie {
            get {
                return ResourceManager.GetString("walkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Wrench&quot;.
        /// </summary>
        public static string wrench {
            get {
                return ResourceManager.GetString("wrench", resourceCulture);
            }
        }
    }
}
