//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.items {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.items.ItemRes", typeof(ItemRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle avanzado.
        /// </summary>
        public static string advanced_rifle {
            get {
                return ResourceManager.GetString("advanced_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistola penetrante.
        /// </summary>
        public static string ap_pistol {
            get {
                return ResourceManager.GetString("ap_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle de asalto.
        /// </summary>
        public static string assault_rifle {
            get {
                return ResourceManager.GetString("assault_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta de asalto.
        /// </summary>
        public static string assault_shotgun {
            get {
                return ResourceManager.GetString("assault_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMG de asalto.
        /// </summary>
        public static string assault_smg {
            get {
                return ResourceManager.GetString("assault_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cebo.
        /// </summary>
        public static string bait {
            get {
                return ResourceManager.GetString("bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bate de baseball.
        /// </summary>
        public static string bat {
            get {
                return ResourceManager.GetString("bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Botellín de cerveza.
        /// </summary>
        public static string beer_bottle {
            get {
                return ResourceManager.GetString("beer_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pack de cervezas.
        /// </summary>
        public static string beer_pack {
            get {
                return ResourceManager.GetString("beer_pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle bullpup.
        /// </summary>
        public static string bullpup_rifle {
            get {
                return ResourceManager.GetString("bullpup_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta bullpup.
        /// </summary>
        public static string bullpup_shotgun {
            get {
                return ResourceManager.GetString("bullpup_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hamburguesa.
        /// </summary>
        public static string burger {
            get {
                return ResourceManager.GetString("burger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cámara de fotos.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caramelos.
        /// </summary>
        public static string candy {
            get {
                return ResourceManager.GetString("candy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carabina.
        /// </summary>
        public static string carbine_rifle {
            get {
                return ResourceManager.GetString("carbine_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Botella de cava.
        /// </summary>
        public static string cava_bottle {
            get {
                return ResourceManager.GetString("cava_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cigarrillos RedWood.
        /// </summary>
        public static string cigarettes {
            get {
                return ResourceManager.GetString("cigarettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Café.
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FunCola.
        /// </summary>
        public static string cola {
            get {
                return ResourceManager.GetString("cola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDW de combate.
        /// </summary>
        public static string combat_pdw {
            get {
                return ResourceManager.GetString("combat_pdw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle compacto.
        /// </summary>
        public static string compact_rifle {
            get {
                return ResourceManager.GetString("compact_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palanca.
        /// </summary>
        public static string crowbar {
            get {
                return ResourceManager.GetString("crowbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta de dos cañones.
        /// </summary>
        public static string double_barrel_shotgun {
            get {
                return ResourceManager.GetString("double_barrel_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bebida energética.
        /// </summary>
        public static string energy_drink {
            get {
                return ResourceManager.GetString("energy_drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pescado.
        /// </summary>
        public static string fish {
            get {
                return ResourceManager.GetString("fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caña de pescar.
        /// </summary>
        public static string fishing_rod {
            get {
                return ResourceManager.GetString("fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Linterna.
        /// </summary>
        public static string flashlight {
            get {
                return ResourceManager.GetString("flashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palo de golf.
        /// </summary>
        public static string golf_club {
            get {
                return ResourceManager.GetString("golf_club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Martillo.
        /// </summary>
        public static string hammer {
            get {
                return ResourceManager.GetString("hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacha.
        /// </summary>
        public static string hatchet {
            get {
                return ResourceManager.GetString("hatchet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistola pesada.
        /// </summary>
        public static string heavy_pistol {
            get {
                return ResourceManager.GetString("heavy_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta pesada.
        /// </summary>
        public static string heavy_shotgun {
            get {
                return ResourceManager.GetString("heavy_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Francotirador pesado.
        /// </summary>
        public static string heavy_sniper {
            get {
                return ResourceManager.GetString("heavy_sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perrito caliente.
        /// </summary>
        public static string hotdog {
            get {
                return ResourceManager.GetString("hotdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lata de gasolina.
        /// </summary>
        public static string jerrycan {
            get {
                return ResourceManager.GetString("jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zumo.
        /// </summary>
        public static string juice {
            get {
                return ResourceManager.GetString("juice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuchillo.
        /// </summary>
        public static string knife {
            get {
                return ResourceManager.GetString("knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puño americano.
        /// </summary>
        public static string knucle_duster {
            get {
                return ResourceManager.GetString("knucle_duster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistola automática.
        /// </summary>
        public static string machine_pistol {
            get {
                return ResourceManager.GetString("machine_pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle de precisión.
        /// </summary>
        public static string marksman_rifle {
            get {
                return ResourceManager.GetString("marksman_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Micro SMG.
        /// </summary>
        public static string micro_smg {
            get {
                return ResourceManager.GetString("micro_smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistola.
        /// </summary>
        public static string pistol {
            get {
                return ResourceManager.GetString("pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pistola 50.
        /// </summary>
        public static string pistol_50 {
            get {
                return ResourceManager.GetString("pistol_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Munición de pistola.
        /// </summary>
        public static string pistol_ammo {
            get {
                return ResourceManager.GetString("pistol_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta.
        /// </summary>
        public static string pump_shotgun {
            get {
                return ResourceManager.GetString("pump_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revólver.
        /// </summary>
        public static string revolver {
            get {
                return ResourceManager.GetString("revolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Munición de rifle de asalto.
        /// </summary>
        public static string rifle_ammo {
            get {
                return ResourceManager.GetString("rifle_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sandwich.
        /// </summary>
        public static string sandwich {
            get {
                return ResourceManager.GetString("sandwich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escopeta recortada.
        /// </summary>
        public static string sawn_off_shotgun {
            get {
                return ResourceManager.GetString("sawn_off_shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Munición de escopeta.
        /// </summary>
        public static string shotgun_ammo {
            get {
                return ResourceManager.GetString("shotgun_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono móvil.
        /// </summary>
        public static string smartphone {
            get {
                return ResourceManager.GetString("smartphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMG.
        /// </summary>
        public static string smg {
            get {
                return ResourceManager.GetString("smg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Munición de metralleta.
        /// </summary>
        public static string smg_ammo {
            get {
                return ResourceManager.GetString("smg_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Munición de rifle de francotirador.
        /// </summary>
        public static string sniper_ammo {
            get {
                return ResourceManager.GetString("sniper_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rifle de francotirador.
        /// </summary>
        public static string sniper_rifle {
            get {
                return ResourceManager.GetString("sniper_rifle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carabina especial.
        /// </summary>
        public static string special_carbine {
            get {
                return ResourceManager.GetString("special_carbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos robados.
        /// </summary>
        public static string stolen_items {
            get {
                return ResourceManager.GetString("stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Navaja.
        /// </summary>
        public static string switchblade {
            get {
                return ResourceManager.GetString("switchblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Walkie-Talkie.
        /// </summary>
        public static string walkie {
            get {
                return ResourceManager.GetString("walkie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llave de tubo.
        /// </summary>
        public static string wrench {
            get {
                return ResourceManager.GetString("wrench", resourceCulture);
            }
        }
    }
}
