//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.error {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.error.ErrRes", typeof(ErrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas un accesorio equipado..
        /// </summary>
        public static string accessory_equiped {
            get {
                return ResourceManager.GetString("accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ninguna duda con ese identificador..
        /// </summary>
        public static string admin_ticket_not_found {
            get {
                return ResourceManager.GetString("admin_ticket_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo pertenece a la administración..
        /// </summary>
        public static string admin_vehicle {
            get {
                return ResourceManager.GetString("admin_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás ejerciendo la prostitución..
        /// </summary>
        public static string already_fucking {
            get {
                return ResourceManager.GetString("already_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás recogiendo la basura..
        /// </summary>
        public static string already_garbage {
            get {
                return ResourceManager.GetString("already_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás en mitad de una ruta de trabajo..
        /// </summary>
        public static string already_in_route {
            get {
                return ResourceManager.GetString("already_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás forzando una cerradura..
        /// </summary>
        public static string already_lockpicking {
            get {
                return ResourceManager.GetString("already_lockpicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes creado un canal de radio..
        /// </summary>
        public static string already_owned_channel {
            get {
                return ResourceManager.GetString("already_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás en medio de una llamada telefónica..
        /// </summary>
        public static string already_phone_talking {
            get {
                return ResourceManager.GetString("already_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas una bolsa equipada..
        /// </summary>
        public static string bag_equiped {
            get {
                return ResourceManager.GetString("bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona destinataria no tiene ninguna cuenta bancaria..
        /// </summary>
        public static string bank_account_not_found {
            get {
                return ResourceManager.GetString("bank_account_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un fallo al procesar la transacción..
        /// </summary>
        public static string bank_general_error {
            get {
                return ResourceManager.GetString("bank_general_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta no dispone de la cantidad requerida..
        /// </summary>
        public static string bank_not_enough_money {
            get {
                return ResourceManager.GetString("bank_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un objeto en tus manos..
        /// </summary>
        public static string both_hand_occupied {
            get {
                return ResourceManager.GetString("both_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ninguna unidad a la venta..
        /// </summary>
        public static string business_clothes_not_available {
            get {
                return ResourceManager.GetString("business_clothes_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El negocio está cerrado con llave..
        /// </summary>
        public static string business_locked {
            get {
                return ResourceManager.GetString("business_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes esperar antes de volver a enviar una duda..
        /// </summary>
        public static string cant_send_multiple_help_requests {
            get {
                return ResourceManager.GetString("cant_send_multiple_help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes reconearte a ti mismo..
        /// </summary>
        public static string cant_spect_self {
            get {
                return ResourceManager.GetString("cant_spect_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes arrancar mientras tienes sexo con una prostituta..
        /// </summary>
        public static string cant_toogle_engine_while_fucking {
            get {
                return ResourceManager.GetString("cant_toogle_engine_while_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes la licencia de turismos..
        /// </summary>
        public static string car_license_achieved {
            get {
                return ResourceManager.GetString("car_license_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas tener al menos {0}$ en el banco para comprar el vehículo..
        /// </summary>
        public static string carshop_no_money {
            get {
                return ResourceManager.GetString("carshop_no_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los sitios de aparcamiento del concesionario están ocupados..
        /// </summary>
        public static string carshop_spawn_occupied {
            get {
                return ResourceManager.GetString("carshop_spawn_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te has podido conectar al canal de radiofrecuencia..
        /// </summary>
        public static string channel_not_found {
            get {
                return ResourceManager.GetString("channel_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente debe estar en el asiento del conductor..
        /// </summary>
        public static string client_not_vehicle_driving {
            get {
                return ResourceManager.GetString("client_not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún contacto en la agenda..
        /// </summary>
        public static string contact_list_empty {
            get {
                return ResourceManager.GetString("contact_list_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bájate de la moto para entregar el pedido..
        /// </summary>
        public static string deliver_in_vehicle {
            get {
                return ResourceManager.GetString("deliver_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para presentarte al examen..
        /// </summary>
        public static string driving_school_money {
            get {
                return ResourceManager.GetString("driving_school_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas unos pendientes equipados..
        /// </summary>
        public static string ear_equiped {
            get {
                return ResourceManager.GetString("ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas cumplir {0} pagas más hasta poder dejar el empleo..
        /// </summary>
        public static string employee_cooldown {
            get {
                return ResourceManager.GetString("employee_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo ya tiene el motor encendido..
        /// </summary>
        public static string engine_already_started {
            get {
                return ResourceManager.GetString("engine_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes apagar el motor del vehículo..
        /// </summary>
        public static string engine_on {
            get {
                return ResourceManager.GetString("engine_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay suficiente dinero en el arca de facción..
        /// </summary>
        public static string faction_not_enough_money {
            get {
                return ResourceManager.GetString("faction_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el aviso seleccionado..
        /// </summary>
        public static string faction_warning_not_found {
            get {
                return ResourceManager.GetString("faction_warning_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El aviso seleccionado ya está siendo atendido..
        /// </summary>
        public static string faction_warning_taken {
            get {
                return ResourceManager.GetString("faction_warning_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has tirado de la caña demasiado pronto..
        /// </summary>
        public static string fishing_canceled {
            get {
                return ResourceManager.GetString("fishing_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pez se ha escapado del anzuelo..
        /// </summary>
        public static string fishing_failed {
            get {
                return ResourceManager.GetString("fishing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes recoger basura desde el vehículo..
        /// </summary>
        public static string garbage_in_vehicle {
            get {
                return ResourceManager.GetString("garbage_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas unas gafas equipadas..
        /// </summary>
        public static string glasses_equiped {
            get {
                return ResourceManager.GetString("glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas tener al menos {0}$ para cambiar tu look..
        /// </summary>
        public static string haircut_money {
            get {
                return ResourceManager.GetString("haircut_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas un sombrero equipado..
        /// </summary>
        public static string hat_equiped {
            get {
                return ResourceManager.GetString("hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes ofrecerte un servicio a ti mismo..
        /// </summary>
        public static string hooker_offered_himself {
            get {
                return ResourceManager.GetString("hooker_offered_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casa ya está en alquiler..
        /// </summary>
        public static string house_already_rentable {
            get {
                return ResourceManager.GetString("house_already_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de interior debe estar entre 0 y {0}..
        /// </summary>
        public static string house_interior_modify {
            get {
                return ResourceManager.GetString("house_interior_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La casa está cerrada con llave..
        /// </summary>
        public static string house_locked {
            get {
                return ResourceManager.GetString("house_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casa no está en venta..
        /// </summary>
        public static string house_not_buyable {
            get {
                return ResourceManager.GetString("house_not_buyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ninguna casa con ese identificador..
        /// </summary>
        public static string house_not_exists {
            get {
                return ResourceManager.GetString("house_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dispones del dinero necesario en tu cuenta bancaria para comprar esta casa..
        /// </summary>
        public static string house_not_money {
            get {
                return ResourceManager.GetString("house_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta casa no está en alquiler..
        /// </summary>
        public static string house_not_rentable {
            get {
                return ResourceManager.GetString("house_not_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede vender la casa ya que está ocupada..
        /// </summary>
        public static string house_occupied {
            get {
                return ResourceManager.GetString("house_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio de la casa debe ser superior a 0$..
        /// </summary>
        public static string house_price_modify {
            get {
                return ResourceManager.GetString("house_price_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio de alquiler de la casa debe ser superior a 0$..
        /// </summary>
        public static string house_rental_modify {
            get {
                return ResourceManager.GetString("house_rental_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error en la venta de la casa. Comprueba que sigue a nombre de su dueño..
        /// </summary>
        public static string house_sell_generic {
            get {
                return ResourceManager.GetString("house_sell_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado de la casa tiene que estar entre 0 y 2..
        /// </summary>
        public static string house_status_modify {
            get {
                return ResourceManager.GetString("house_status_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes nada consumible en la mano..
        /// </summary>
        public static string item_not_consumable {
            get {
                return ResourceManager.GetString("item_not_consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cancelado tu entrega por abandonar el vehículo de trabajo..
        /// </summary>
        public static string job_vehicle_abandoned {
            get {
                return ResourceManager.GetString("job_vehicle_abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún objeto en tu mano izquierda..
        /// </summary>
        public static string left_hand_empty {
            get {
                return ResourceManager.GetString("left_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un objeto en tu mano izquierda..
        /// </summary>
        public static string left_hand_occupied {
            get {
                return ResourceManager.GetString("left_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has suspendido el examen práctico..
        /// </summary>
        public static string license_drive_failed {
            get {
                return ResourceManager.GetString("license_drive_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has suspendido el examen teórico..
        /// </summary>
        public static string license_exam_failed {
            get {
                return ResourceManager.GetString("license_exam_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has suspendido el examen por no subir en el vehículo..
        /// </summary>
        public static string license_failed_not_in_vehicle {
            get {
                return ResourceManager.GetString("license_failed_not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes muy poca sangre como para recibir una extracción..
        /// </summary>
        public static string low_blood {
            get {
                return ResourceManager.GetString("low_blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya llevas una máscara equipada..
        /// </summary>
        public static string mask_equiped {
            get {
                return ResourceManager.GetString("mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los mensajes privados sólo se pueden usar con miembros del staff..
        /// </summary>
        public static string mps_only_admin {
            get {
                return ResourceManager.GetString("mps_only_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ha conseguido un resultado negativo..
        /// </summary>
        public static string negative_result {
            get {
                return ResourceManager.GetString("negative_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ningún accesorio..
        /// </summary>
        public static string no_accessory_bought {
            get {
                return ResourceManager.GetString("no_accessory_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ningún accesorio equipado..
        /// </summary>
        public static string no_accessory_equiped {
            get {
                return ResourceManager.GetString("no_accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay miembros del staff disponibles en este momento, vuelve a intentarlo en un rato por favor..
        /// </summary>
        public static string no_admins_on_duty_atm {
            get {
                return ResourceManager.GetString("no_admins_on_duty_atm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ninguna bolsa..
        /// </summary>
        public static string no_bag_bought {
            get {
                return ResourceManager.GetString("no_bag_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ninguna bolsa equipada..
        /// </summary>
        public static string no_bag_equiped {
            get {
                return ResourceManager.GetString("no_bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No queda ninguna unidad de sangre..
        /// </summary>
        public static string no_blood_left {
            get {
                return ResourceManager.GetString("no_blood_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has seleccionado ningún personaje..
        /// </summary>
        public static string no_character_selected {
            get {
                return ResourceManager.GetString("no_character_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ninguna prenda en el armario..
        /// </summary>
        public static string no_clothes_in_wardrobe {
            get {
                return ResourceManager.GetString("no_clothes_in_wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ningunos pendientes..
        /// </summary>
        public static string no_ear_bought {
            get {
                return ResourceManager.GetString("no_ear_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ningunos pendientes equipados..
        /// </summary>
        public static string no_ear_equiped {
            get {
                return ResourceManager.GetString("no_ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes pescado para vender..
        /// </summary>
        public static string no_fish_sellable {
            get {
                return ResourceManager.GetString("no_fish_sellable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes una caña en la mano derecha..
        /// </summary>
        public static string no_fishing_rod {
            get {
                return ResourceManager.GetString("no_fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ningunas gafas..
        /// </summary>
        public static string no_glasses_bought {
            get {
                return ResourceManager.GetString("no_glasses_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ningunas gafas equipadas..
        /// </summary>
        public static string no_glasses_equiped {
            get {
                return ResourceManager.GetString("no_glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ningún sombrero..
        /// </summary>
        public static string no_hat_bought {
            get {
                return ResourceManager.GetString("no_hat_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ningún sombrero equipado..
        /// </summary>
        public static string no_hat_equiped {
            get {
                return ResourceManager.GetString("no_hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún objeto en el inventario..
        /// </summary>
        public static string no_items_inventory {
            get {
                return ResourceManager.GetString("no_items_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún objeto cerca de ti..
        /// </summary>
        public static string no_items_near {
            get {
                return ResourceManager.GetString("no_items_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El maletero del vehículo está vacío..
        /// </summary>
        public static string no_items_trunk {
            get {
                return ResourceManager.GetString("no_items_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has comprado ninguna máscara..
        /// </summary>
        public static string no_mask_bought {
            get {
                return ResourceManager.GetString("no_mask_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ninguna máscara equipada..
        /// </summary>
        public static string no_mask_equiped {
            get {
                return ResourceManager.GetString("no_mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ningún control policial guardado..
        /// </summary>
        public static string no_police_controls {
            get {
                return ResourceManager.GetString("no_police_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te han ofrecido repintar tu vehículo..
        /// </summary>
        public static string no_repaint_offered {
            get {
                return ResourceManager.GetString("no_repaint_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te han ofrecido una reparación..
        /// </summary>
        public static string no_repair_offered {
            get {
                return ResourceManager.GetString("no_repair_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nadie te ha ofrecido un servicio sexual..
        /// </summary>
        public static string no_service_offered {
            get {
                return ResourceManager.GetString("no_service_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El taxista no puede seleccionar ninguna ruta..
        /// </summary>
        public static string no_taxi_driver {
            get {
                return ResourceManager.GetString("no_taxi_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el teléfono en la mano..
        /// </summary>
        public static string no_telephone_hand {
            get {
                return ResourceManager.GetString("no_telephone_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún vehículo cerca..
        /// </summary>
        public static string no_vehicles_near {
            get {
                return ResourceManager.GetString("no_vehicles_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún equipo de retransmisión en la mano..
        /// </summary>
        public static string no_walkie_in_hand {
            get {
                return ResourceManager.GetString("no_walkie_in_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes las llaves de este vehículo..
        /// </summary>
        public static string not_car_keys {
            get {
                return ResourceManager.GetString("not_car_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has atendido ningún pedido..
        /// </summary>
        public static string not_delivering_order {
            get {
                return ResourceManager.GetString("not_delivering_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres repartidor de comida rápida..
        /// </summary>
        public static string not_fastfood {
            get {
                return ResourceManager.GetString("not_fastfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo no es un barco pesquero..
        /// </summary>
        public static string not_fishing_boat {
            get {
                return ResourceManager.GetString("not_fishing_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna tienda de pesca..
        /// </summary>
        public static string not_fishing_business {
            get {
                return ResourceManager.GetString("not_fishing_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna zona de pesca..
        /// </summary>
        public static string not_fishing_zone {
            get {
                return ResourceManager.GetString("not_fishing_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna gasolinera..
        /// </summary>
        public static string not_fuel_station_near {
            get {
                return ResourceManager.GetString("not_fuel_station_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ninguna bolsa de basura cerca..
        /// </summary>
        public static string not_garbage_near {
            get {
                return ResourceManager.GetString("not_garbage_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres prostituta..
        /// </summary>
        public static string not_hooker {
            get {
                return ResourceManager.GetString("not_hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en la puerta de ninguna casa ni negocio..
        /// </summary>
        public static string not_house_business {
            get {
                return ResourceManager.GetString("not_house_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ninguna casa cerca de ti..
        /// </summary>
        public static string not_house_near {
            get {
                return ResourceManager.GetString("not_house_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás haciendo el examen práctico de conducción..
        /// </summary>
        public static string not_in_car_practice {
            get {
                return ResourceManager.GetString("not_in_car_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ningún concesionario..
        /// </summary>
        public static string not_in_carshop {
            get {
                return ResourceManager.GetString("not_in_carshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ningún taller..
        /// </summary>
        public static string not_in_mechanic_workshop {
            get {
                return ResourceManager.GetString("not_in_mechanic_workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna tienda de empeños..
        /// </summary>
        public static string not_in_pawn_show {
            get {
                return ResourceManager.GetString("not_in_pawn_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás haciendo ninguna ruta de trabajo..
        /// </summary>
        public static string not_in_route {
            get {
                return ResourceManager.GetString("not_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás subido en ningún vehículo..
        /// </summary>
        public static string not_in_vehicle {
            get {
                return ResourceManager.GetString("not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No perteneces a la misma facción que este vehículo..
        /// </summary>
        public static string not_in_vehicle_faction {
            get {
                return ResourceManager.GetString("not_in_vehicle_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el trabajo necesario para acceder a este vehículo..
        /// </summary>
        public static string not_in_vehicle_job {
            get {
                return ResourceManager.GetString("not_in_vehicle_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes estar dentro de un coche..
        /// </summary>
        public static string not_in_vehicle_type_car {
            get {
                return ResourceManager.GetString("not_in_vehicle_type_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no está participando en una entrevista..
        /// </summary>
        public static string not_on_air {
            get {
                return ResourceManager.GetString("not_on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes creado ningún canal de radio..
        /// </summary>
        public static string not_owned_channel {
            get {
                return ResourceManager.GetString("not_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes aparcar tu vehículo aquí..
        /// </summary>
        public static string not_parking_allowed {
            get {
                return ResourceManager.GetString("not_parking_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás cerca de ningún estacionamiento..
        /// </summary>
        public static string not_parking_near {
            get {
                return ResourceManager.GetString("not_parking_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás haciendo ninguna llamada telefónica..
        /// </summary>
        public static string not_phone_talking {
            get {
                return ResourceManager.GetString("not_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres el comisario del departamento policial..
        /// </summary>
        public static string not_police_chief {
            get {
                return ResourceManager.GetString("not_police_chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0} productos para llevar a cabo la acción..
        /// </summary>
        public static string not_required_products {
            get {
                return ResourceManager.GetString("not_required_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en el desguace municipal..
        /// </summary>
        public static string not_scrapyard_near {
            get {
                return ResourceManager.GetString("not_scrapyard_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te encuentras de servicio..
        /// </summary>
        public static string not_service {
            get {
                return ResourceManager.GetString("not_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás reconeando a nadie..
        /// </summary>
        public static string not_spectating {
            get {
                return ResourceManager.GetString("not_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás autorizado a probar este vehículo..
        /// </summary>
        public static string not_testing_vehicle {
            get {
                return ResourceManager.GetString("not_testing_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres ladrón..
        /// </summary>
        public static string not_thief {
            get {
                return ResourceManager.GetString("not_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres transportista..
        /// </summary>
        public static string not_trucker {
            get {
                return ResourceManager.GetString("not_trucker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ningún taller ni tienes una grúa cerca..
        /// </summary>
        public static string not_valid_repair_place {
            get {
                return ResourceManager.GetString("not_valid_repair_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás conduciendo el vehículo..
        /// </summary>
        public static string not_vehicle_driving {
            get {
                return ResourceManager.GetString("not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en el asiento del copiloto..
        /// </summary>
        public static string not_vehicle_passenger {
            get {
                return ResourceManager.GetString("not_vehicle_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éste no es tu vehículo de trabajo..
        /// </summary>
        public static string not_your_job_vehicle {
            get {
                return ResourceManager.GetString("not_your_job_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo ya está participando en una entrevista..
        /// </summary>
        public static string on_air {
            get {
                return ResourceManager.GetString("on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás atendiendo un pedido..
        /// </summary>
        public static string order_delivering {
            get {
                return ResourceManager.GetString("order_delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay ningún pedido en la lista para atender..
        /// </summary>
        public static string order_none {
            get {
                return ResourceManager.GetString("order_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pedido ya ha sido atendido por otra persona..
        /// </summary>
        public static string order_taken {
            get {
                return ResourceManager.GetString("order_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente se ha cansado de esperar a su pedido..
        /// </summary>
        public static string order_timeout {
            get {
                return ResourceManager.GetString("order_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No caben más vehículos en este aparcamiento..
        /// </summary>
        public static string parking_full {
            get {
                return ResourceManager.GetString("parking_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo puedes asignar una casa a un garaje privado..
        /// </summary>
        public static string parking_not_garage {
            get {
                return ResourceManager.GetString("parking_not_garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para sacar el vehículo del aparcamiento..
        /// </summary>
        public static string parking_not_money {
            get {
                return ResourceManager.GetString("parking_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo ya pertenece a una facción..
        /// </summary>
        public static string player_already_faction {
            get {
                return ResourceManager.GetString("player_already_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás pescando..
        /// </summary>
        public static string player_already_fishing {
            get {
                return ResourceManager.GetString("player_already_fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás haciendo un puente al vehículo..
        /// </summary>
        public static string player_already_hotwiring {
            get {
                return ResourceManager.GetString("player_already_hotwiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo ya tiene un trabajo..
        /// </summary>
        public static string player_already_job {
            get {
                return ResourceManager.GetString("player_already_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu licencia aún está vigente..
        /// </summary>
        public static string player_already_license {
            get {
                return ResourceManager.GetString("player_already_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás robando objetos..
        /// </summary>
        public static string player_already_stealing {
            get {
                return ResourceManager.GetString("player_already_stealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar el chat dentro de la sala de selección de personaje..
        /// </summary>
        public static string player_cant_chat {
            get {
                return ResourceManager.GetString("player_cant_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes usar comandos dentro de la sala de selección de personaje..
        /// </summary>
        public static string player_cant_command {
            get {
                return ResourceManager.GetString("player_cant_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes hacer un puente en tu propio vehículo..
        /// </summary>
        public static string player_cant_hotwire_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_hotwire_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes forzar la puerta de tu vehículo..
        /// </summary>
        public static string player_cant_lockpick_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_lockpick_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay nada que robar cerca..
        /// </summary>
        public static string player_cant_rob {
            get {
                return ResourceManager.GetString("player_cant_rob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes robar en tu propia casa..
        /// </summary>
        public static string player_cant_rob_own_house {
            get {
                return ResourceManager.GetString("player_cant_rob_own_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes robar en tu propio vehículo..
        /// </summary>
        public static string player_cant_rob_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_rob_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no puedes ser tú mismo..
        /// </summary>
        public static string player_cant_self {
            get {
                return ResourceManager.GetString("player_cant_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún sigues nervioso por el último robo, podrás volver a robar pasada 1 hora..
        /// </summary>
        public static string player_cooldown_thief {
            get {
                return ResourceManager.GetString("player_cooldown_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te puedes multar a ti mismo..
        /// </summary>
        public static string player_fined_himself {
            get {
                return ResourceManager.GetString("player_fined_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te puedes esposar a ti mismo..
        /// </summary>
        public static string player_handcuffed_himself {
            get {
                return ResourceManager.GetString("player_handcuffed_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes la documentación en regla..
        /// </summary>
        public static string player_has_identification {
            get {
                return ResourceManager.GetString("player_has_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un empleo..
        /// </summary>
        public static string player_has_job {
            get {
                return ResourceManager.GetString("player_has_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un seguro médico vigente..
        /// </summary>
        public static string player_has_medical_insurance {
            get {
                return ResourceManager.GetString("player_has_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes una licencia de taxis..
        /// </summary>
        public static string player_has_taxi_license {
            get {
                return ResourceManager.GetString("player_has_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya está atendiendo un aviso..
        /// </summary>
        public static string player_have_faction_warning {
            get {
                return ResourceManager.GetString("player_have_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás viviendo de alquiler en una casa..
        /// </summary>
        public static string player_house_rented {
            get {
                return ResourceManager.GetString("player_house_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No te puedes inculpar a ti mismo..
        /// </summary>
        public static string player_incriminated_himself {
            get {
                return ResourceManager.GetString("player_incriminated_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes hacer esto desde dentro del vehículo.
        /// </summary>
        public static string player_inside_vehicle {
            get {
                return ResourceManager.GetString("player_inside_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes hacer eso estando inconsciente..
        /// </summary>
        public static string player_is_dead {
            get {
                return ResourceManager.GetString("player_is_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has pasado el tiempo requerido en tu trabajo actual..
        /// </summary>
        public static string player_job_restriction {
            get {
                return ResourceManager.GetString("player_job_restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes acceder a este empleo estando en una facción estatal..
        /// </summary>
        public static string player_job_state_faction {
            get {
                return ResourceManager.GetString("player_job_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador tiene demasiados vehículos prestados..
        /// </summary>
        public static string player_keys_full {
            get {
                return ResourceManager.GetString("player_keys_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes nada que usar como cebo..
        /// </summary>
        public static string player_no_baits {
            get {
                return ResourceManager.GetString("player_no_baits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna facción..
        /// </summary>
        public static string player_no_faction {
            get {
                return ResourceManager.GetString("player_no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No has seleccionado ninguna multa a pagar..
        /// </summary>
        public static string player_no_fines {
            get {
                return ResourceManager.GetString("player_no_fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas ninguna lata de gasolina en la mano..
        /// </summary>
        public static string player_no_jerrycan {
            get {
                return ResourceManager.GetString("player_no_jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún empleo..
        /// </summary>
        public static string player_no_job {
            get {
                return ResourceManager.GetString("player_no_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres el dueño del negocio..
        /// </summary>
        public static string player_not_business_owner {
            get {
                return ResourceManager.GetString("player_not_business_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay nadie llamándote en este momento..
        /// </summary>
        public static string player_not_called {
            get {
                return ResourceManager.GetString("player_not_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes estar en un coche para usar estas animaciones..
        /// </summary>
        public static string player_not_car {
            get {
                return ResourceManager.GetString("player_not_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no se encuentra inconsciente..
        /// </summary>
        public static string player_not_dead {
            get {
                return ResourceManager.GetString("player_not_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en la autoescuela..
        /// </summary>
        public static string player_not_driving_school {
            get {
                return ResourceManager.GetString("player_not_driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No perteneces al departamento de emergencias..
        /// </summary>
        public static string player_not_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No llevas suficiente dinero encima..
        /// </summary>
        public static string player_not_enough_money {
            get {
                return ResourceManager.GetString("player_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes suficiente rango dentro de LSPD para retirar munición ni armas..
        /// </summary>
        public static string player_not_enough_police_rank {
            get {
                return ResourceManager.GetString("player_not_enough_police_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para pagar tus multas..
        /// </summary>
        public static string player_not_fine_money {
            get {
                return ResourceManager.GetString("player_not_fine_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres pescador..
        /// </summary>
        public static string player_not_fisherman {
            get {
                return ResourceManager.GetString("player_not_fisherman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no se encuentra conectado..
        /// </summary>
        public static string player_not_found {
            get {
                return ResourceManager.GetString("player_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes acceso a este garaje..
        /// </summary>
        public static string player_not_garage_access {
            get {
                return ResourceManager.GetString("player_not_garage_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres basurero..
        /// </summary>
        public static string player_not_garbage {
            get {
                return ResourceManager.GetString("player_not_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres el propietario de esta casa..
        /// </summary>
        public static string player_not_house_owner {
            get {
                return ResourceManager.GetString("player_not_house_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no está herido..
        /// </summary>
        public static string player_not_hurt {
            get {
                return ResourceManager.GetString("player_not_hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para sacarte la documentación..
        /// </summary>
        public static string player_not_identification_money {
            get {
                return ResourceManager.GetString("player_not_identification_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás dentro de ninguna casa..
        /// </summary>
        public static string player_not_in_house {
            get {
                return ResourceManager.GetString("player_not_in_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes estar en la parte de atras izquierda de la furgoneta de retransmisión de Weazel News..
        /// </summary>
        public static string player_not_in_news_van {
            get {
                return ResourceManager.GetString("player_not_in_news_van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes estar en la parte de atras derecha de la furgoneta..
        /// </summary>
        public static string player_not_in_right_rear {
            get {
                return ResourceManager.GetString("player_not_in_right_rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en los vestuarios de comisaria..
        /// </summary>
        public static string player_not_in_room_lockers {
            get {
                return ResourceManager.GetString("player_not_in_room_lockers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo no se encuentra en tu facción..
        /// </summary>
        public static string player_not_in_same_faction {
            get {
                return ResourceManager.GetString("player_not_in_same_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en la entrada de los calabozos..
        /// </summary>
        public static string player_not_jail_area {
            get {
                return ResourceManager.GetString("player_not_jail_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No eres mecánico..
        /// </summary>
        public static string player_not_mechanic {
            get {
                return ResourceManager.GetString("player_not_mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún seguro médico..
        /// </summary>
        public static string player_not_medical_insurance {
            get {
                return ResourceManager.GetString("player_not_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para sacarte el seguro médico..
        /// </summary>
        public static string player_not_medical_insurance_money {
            get {
                return ResourceManager.GetString("player_not_medical_insurance_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No perteneces a Weazel News..
        /// </summary>
        public static string player_not_news_faction {
            get {
                return ResourceManager.GetString("player_not_news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás de servicio como staff..
        /// </summary>
        public static string player_not_on_admin_duty {
            get {
                return ResourceManager.GetString("player_not_on_admin_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás de servicio ahora mismo..
        /// </summary>
        public static string player_not_on_duty {
            get {
                return ResourceManager.GetString("player_not_on_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes atenderte a ti mismo..
        /// </summary>
        public static string player_not_own_death {
            get {
                return ResourceManager.GetString("player_not_own_death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No perteneces al departamento de policía ni al de emergencias..
        /// </summary>
        public static string player_not_police_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_police_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No perteneces al departamento de policía..
        /// </summary>
        public static string player_not_police_faction {
            get {
                return ResourceManager.GetString("player_not_police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No dispones del dinero necesario en mano para pagar la fianza de alquiler..
        /// </summary>
        public static string player_not_rent_money {
            get {
                return ResourceManager.GetString("player_not_rent_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes una caña en la mano ni estás en ningún pesquero..
        /// </summary>
        public static string player_not_rod_boat {
            get {
                return ResourceManager.GetString("player_not_rod_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en ninguna facción estatal..
        /// </summary>
        public static string player_not_state_faction {
            get {
                return ResourceManager.GetString("player_not_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún objeto robado..
        /// </summary>
        public static string player_not_stolen_items {
            get {
                return ResourceManager.GetString("player_not_stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes la licencia de taxi en regla..
        /// </summary>
        public static string player_not_taxi_license {
            get {
                return ResourceManager.GetString("player_not_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Necesitas {0}$ para sacarte la licencia de taxis..
        /// </summary>
        public static string player_not_taxi_license_money {
            get {
                return ResourceManager.GetString("player_not_taxi_license_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en el centro de la ciudad..
        /// </summary>
        public static string player_not_thief_area {
            get {
                return ResourceManager.GetString("player_not_thief_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás en el ayuntamiento..
        /// </summary>
        public static string player_not_townhall {
            get {
                return ResourceManager.GetString("player_not_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes llaves de este vehículo..
        /// </summary>
        public static string player_not_veh_owner {
            get {
                return ResourceManager.GetString("player_not_veh_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás repostando un vehículo..
        /// </summary>
        public static string player_refueling {
            get {
                return ResourceManager.GetString("player_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes cachearte a ti mismo..
        /// </summary>
        public static string player_searched_himself {
            get {
                return ResourceManager.GetString("player_searched_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador está reconeando a otro jugador..
        /// </summary>
        public static string player_spectating {
            get {
                return ResourceManager.GetString("player_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has abandonado el vehículo y has dejado de intentar hacer el puente..
        /// </summary>
        public static string player_stopped_hotwire {
            get {
                return ResourceManager.GetString("player_stopped_hotwire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estás demasiado lejos del jugador objetivo..
        /// </summary>
        public static string player_too_far {
            get {
                return ResourceManager.GetString("player_too_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes documentación, recuerda que es ilegal ir indocumentado..
        /// </summary>
        public static string player_undocumented {
            get {
                return ResourceManager.GetString("player_undocumented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio debe ser mayor a 0$..
        /// </summary>
        public static string price_positive {
            get {
                return ResourceManager.GetString("price_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No estás conectado a ninguna frecuencia de radio..
        /// </summary>
        public static string radio_frequency_none {
            get {
                return ResourceManager.GetString("radio_frequency_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el rango necesario para expulsar miembros..
        /// </summary>
        public static string rank_too_low_dismiss {
            get {
                return ResourceManager.GetString("rank_too_low_dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el rango necesario para cambiar el rango de los miembros..
        /// </summary>
        public static string rank_too_low_rank {
            get {
                return ResourceManager.GetString("rank_too_low_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes el rango necesario para reclutar nuevos miembros..
        /// </summary>
        public static string rank_too_low_recruit {
            get {
                return ResourceManager.GetString("rank_too_low_recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes ningún objeto en tu mano derecha..
        /// </summary>
        public static string right_hand_empty {
            get {
                return ResourceManager.GetString("right_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un objeto en tu mano derecha..
        /// </summary>
        public static string right_hand_occupied {
            get {
                return ResourceManager.GetString("right_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes salir mientras estás robando..
        /// </summary>
        public static string stealing_progress {
            get {
                return ResourceManager.GetString("stealing_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador objetivo tiene la mano derecha ocupada..
        /// </summary>
        public static string target_right_hand_not_empty {
            get {
                return ResourceManager.GetString("target_right_hand_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tienes un tatuaje igual..
        /// </summary>
        public static string tattoo_duplicated {
            get {
                return ResourceManager.GetString("tattoo_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El taxista ya está realizando una ruta..
        /// </summary>
        public static string taxi_has_path {
            get {
                return ResourceManager.GetString("taxi_has_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes realizar una transferencia a tu propia cuenta..
        /// </summary>
        public static string transfer_money_own {
            get {
                return ResourceManager.GetString("transfer_money_own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo ya está abierto..
        /// </summary>
        public static string veh_already_unlocked {
            get {
                return ResourceManager.GetString("veh_already_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo no es adecuado para tu licencia..
        /// </summary>
        public static string vehicle_driving_not_suitable {
            get {
                return ResourceManager.GetString("vehicle_driving_not_suitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes aparcar este vehículo..
        /// </summary>
        public static string vehicle_faction_park {
            get {
                return ResourceManager.GetString("vehicle_faction_park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ningún vehículo para ese identificador..
        /// </summary>
        public static string vehicle_not_exists {
            get {
                return ResourceManager.GetString("vehicle_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este vehículo no se puede bloquear..
        /// </summary>
        public static string vehicle_not_lockable {
            get {
                return ResourceManager.GetString("vehicle_not_lockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éste vehículo no tiene un megáfono instalado..
        /// </summary>
        public static string vehicle_not_megaphone {
            get {
                return ResourceManager.GetString("vehicle_not_megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El vehículo no está aparcado aquí..
        /// </summary>
        public static string vehicle_not_this_parking {
            get {
                return ResourceManager.GetString("vehicle_not_this_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El vehículo ya está siendo repostado..
        /// </summary>
        public static string vehicle_refueling {
            get {
                return ResourceManager.GetString("vehicle_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes arrancar el vehículo mientras está repostando..
        /// </summary>
        public static string vehicle_start_refueling {
            get {
                return ResourceManager.GetString("vehicle_start_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes arrancar el vehículo mientras están sacando armas..
        /// </summary>
        public static string vehicle_start_weapon_unpacking {
            get {
                return ResourceManager.GetString("vehicle_start_weapon_unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El depósito del vehículo está lleno..
        /// </summary>
        public static string vehicle_tank_full {
            get {
                return ResourceManager.GetString("vehicle_tank_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El maletero del vehículo está cerrado..
        /// </summary>
        public static string vehicle_trunk_closed {
            get {
                return ResourceManager.GetString("vehicle_trunk_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay alguien usando el maletero del vehículo..
        /// </summary>
        public static string vehicle_trunk_in_use {
            get {
                return ResourceManager.GetString("vehicle_trunk_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El maletero del vehículo está abierto..
        /// </summary>
        public static string vehicle_trunk_opened {
            get {
                return ResourceManager.GetString("vehicle_trunk_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El vehículo está demasiado lejos..
        /// </summary>
        public static string wanted_vehicle_far {
            get {
                return ResourceManager.GetString("wanted_vehicle_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha lanzado un evento de armas..
        /// </summary>
        public static string weapon_event_on_course {
            get {
                return ResourceManager.GetString("weapon_event_on_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes la licencia de armas vigente..
        /// </summary>
        public static string weapon_license_expired {
            get {
                return ResourceManager.GetString("weapon_license_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El clima debe estar comprendido entre 0 y 14..
        /// </summary>
        public static string weather_value_invalid {
            get {
                return ResourceManager.GetString("weather_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta rueda no necesita ser reparada..
        /// </summary>
        public static string wheel_not_popped {
            get {
                return ResourceManager.GetString("wheel_not_popped", resourceCulture);
            }
        }
    }
}
