//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiredPlayers.messages.error {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiredPlayers.messages.error.ErrRes", typeof(ErrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing an accessory.&quot;.
        /// </summary>
        public static string accessory_equiped {
            get {
                return ResourceManager.GetString("accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;No ticket was found with that identifier.&quot;.
        /// </summary>
        public static string admin_ticket_not_found {
            get {
                return ResourceManager.GetString("admin_ticket_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle can only be accessed by the staff.&quot;.
        /// </summary>
        public static string admin_vehicle {
            get {
                return ResourceManager.GetString("admin_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re in the middle of a service with your client.&quot;.
        /// </summary>
        public static string already_fucking {
            get {
                return ResourceManager.GetString("already_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already collecting garbage.&quot;.
        /// </summary>
        public static string already_garbage {
            get {
                return ResourceManager.GetString("already_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re in the middle of a job route.&quot;.
        /// </summary>
        public static string already_in_route {
            get {
                return ResourceManager.GetString("already_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already lockpicking.&quot;.
        /// </summary>
        public static string already_lockpicking {
            get {
                return ResourceManager.GetString("already_lockpicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a radio channel created.&quot;.
        /// </summary>
        public static string already_owned_channel {
            get {
                return ResourceManager.GetString("already_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already talking to the phone.&quot;.
        /// </summary>
        public static string already_phone_talking {
            get {
                return ResourceManager.GetString("already_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing a bag.&quot;.
        /// </summary>
        public static string bag_equiped {
            get {
                return ResourceManager.GetString("bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s no bank account linked to that person.&quot;.
        /// </summary>
        public static string bank_account_not_found {
            get {
                return ResourceManager.GetString("bank_account_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;An error occurred while processing the operation.&quot;.
        /// </summary>
        public static string bank_general_error {
            get {
                return ResourceManager.GetString("bank_general_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The bank account has not enough funds to process the operation.&quot;.
        /// </summary>
        public static string bank_not_enough_money {
            get {
                return ResourceManager.GetString("bank_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have an item in your hands.&quot;.
        /// </summary>
        public static string both_hand_occupied {
            get {
                return ResourceManager.GetString("both_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There are no clothes for sale.&quot;.
        /// </summary>
        public static string business_clothes_not_available {
            get {
                return ResourceManager.GetString("business_clothes_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This business is locked.&quot;.
        /// </summary>
        public static string business_locked {
            get {
                return ResourceManager.GetString("business_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have to wait before sending a new ticket.&quot;.
        /// </summary>
        public static string cant_send_multiple_help_requests {
            get {
                return ResourceManager.GetString("cant_send_multiple_help_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t spectate yourself.&quot;.
        /// </summary>
        public static string cant_spect_self {
            get {
                return ResourceManager.GetString("cant_spect_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t turn the engine on while having a sex service.&quot;.
        /// </summary>
        public static string cant_toogle_engine_while_fucking {
            get {
                return ResourceManager.GetString("cant_toogle_engine_while_fucking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a car license.&quot;.
        /// </summary>
        public static string car_license_achieved {
            get {
                return ResourceManager.GetString("car_license_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need at least {0}$ in your bank account to purchase this vehicle.&quot;.
        /// </summary>
        public static string carshop_no_money {
            get {
                return ResourceManager.GetString("carshop_no_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;All the parking places of the car dealer are occupied.&quot;.
        /// </summary>
        public static string carshop_spawn_occupied {
            get {
                return ResourceManager.GetString("carshop_spawn_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You couldn&apos;t connect to the radio frequency channel.&quot;.
        /// </summary>
        public static string channel_not_found {
            get {
                return ResourceManager.GetString("channel_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The client must be on driver&apos;s seat.&quot;.
        /// </summary>
        public static string client_not_vehicle_driving {
            get {
                return ResourceManager.GetString("client_not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any contact in your contact list.&quot;.
        /// </summary>
        public static string contact_list_empty {
            get {
                return ResourceManager.GetString("contact_list_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Get down from the motorcycle to deliver the order.&quot;.
        /// </summary>
        public static string deliver_in_vehicle {
            get {
                return ResourceManager.GetString("deliver_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to examinate.&quot;.
        /// </summary>
        public static string driving_school_money {
            get {
                return ResourceManager.GetString("driving_school_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing a pair of earrings.&quot;.
        /// </summary>
        public static string ear_equiped {
            get {
                return ResourceManager.GetString("ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need to get {0} more paydays to leave the job.&quot;.
        /// </summary>
        public static string employee_cooldown {
            get {
                return ResourceManager.GetString("employee_cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle&apos;s engine is already toggled on.&quot;.
        /// </summary>
        public static string engine_already_started {
            get {
                return ResourceManager.GetString("engine_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have to toggle the vehicle engine off.&quot;.
        /// </summary>
        public static string engine_on {
            get {
                return ResourceManager.GetString("engine_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There are not enough funds into the faction&apos;s coffers.&quot;.
        /// </summary>
        public static string faction_not_enough_money {
            get {
                return ResourceManager.GetString("faction_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Couldn&apos;t find the requested report.&quot;.
        /// </summary>
        public static string faction_warning_not_found {
            get {
                return ResourceManager.GetString("faction_warning_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The selected report is being attended.&quot;.
        /// </summary>
        public static string faction_warning_taken {
            get {
                return ResourceManager.GetString("faction_warning_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You reeled too early.&quot;.
        /// </summary>
        public static string fishing_canceled {
            get {
                return ResourceManager.GetString("fishing_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The fish has escaped from the hook.&quot;.
        /// </summary>
        public static string fishing_failed {
            get {
                return ResourceManager.GetString("fishing_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t collect garbage from the vehicle.&quot;.
        /// </summary>
        public static string garbage_in_vehicle {
            get {
                return ResourceManager.GetString("garbage_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing a pair of glasses.&quot;.
        /// </summary>
        public static string glasses_equiped {
            get {
                return ResourceManager.GetString("glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need at least {0}$ to change your look.&quot;.
        /// </summary>
        public static string haircut_money {
            get {
                return ResourceManager.GetString("haircut_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing a hat.&quot;.
        /// </summary>
        public static string hat_equiped {
            get {
                return ResourceManager.GetString("hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can offer a service to yourself.&quot;.
        /// </summary>
        public static string hooker_offered_himself {
            get {
                return ResourceManager.GetString("hooker_offered_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This house is already rentable.&quot;.
        /// </summary>
        public static string house_already_rentable {
            get {
                return ResourceManager.GetString("house_already_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The interior value must be between 0 and {0}.&quot;.
        /// </summary>
        public static string house_interior_modify {
            get {
                return ResourceManager.GetString("house_interior_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This house is locked.&quot;.
        /// </summary>
        public static string house_locked {
            get {
                return ResourceManager.GetString("house_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This house is not for sale.&quot;.
        /// </summary>
        public static string house_not_buyable {
            get {
                return ResourceManager.GetString("house_not_buyable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Couldn&apos;t find any house with that identifier.&quot;.
        /// </summary>
        public static string house_not_exists {
            get {
                return ResourceManager.GetString("house_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required money to buy this house in your bank account.&quot;.
        /// </summary>
        public static string house_not_money {
            get {
                return ResourceManager.GetString("house_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This house is not rentable.&quot;.
        /// </summary>
        public static string house_not_rentable {
            get {
                return ResourceManager.GetString("house_not_rentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t sell the house as it has people living on it.&quot;.
        /// </summary>
        public static string house_occupied {
            get {
                return ResourceManager.GetString("house_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The price of the house must be greater than 0$.&quot;.
        /// </summary>
        public static string house_price_modify {
            get {
                return ResourceManager.GetString("house_price_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This house&apos;s rental price must be greater than 0$.&quot;.
        /// </summary>
        public static string house_rental_modify {
            get {
                return ResourceManager.GetString("house_rental_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s been an error selling the house, check if it&apos;s still yours.&quot;.
        /// </summary>
        public static string house_sell_generic {
            get {
                return ResourceManager.GetString("house_sell_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The state of this house must be between 0 and 2.&quot;.
        /// </summary>
        public static string house_status_modify {
            get {
                return ResourceManager.GetString("house_status_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any consumable in your hand.&quot;.
        /// </summary>
        public static string item_not_consumable {
            get {
                return ResourceManager.GetString("item_not_consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Your delivered has been canceled for leaving your job vehicle.&quot;.
        /// </summary>
        public static string job_vehicle_abandoned {
            get {
                return ResourceManager.GetString("job_vehicle_abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any item in your left hand.&quot;.
        /// </summary>
        public static string left_hand_empty {
            get {
                return ResourceManager.GetString("left_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have an item in your left hand.&quot;.
        /// </summary>
        public static string left_hand_occupied {
            get {
                return ResourceManager.GetString("left_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You failed the practical exam.&quot;.
        /// </summary>
        public static string license_drive_failed {
            get {
                return ResourceManager.GetString("license_drive_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You failed the theoric exam.&quot;.
        /// </summary>
        public static string license_exam_failed {
            get {
                return ResourceManager.GetString("license_exam_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You failed the exam for not returning to your vehicle.&quot;.
        /// </summary>
        public static string license_failed_not_in_vehicle {
            get {
                return ResourceManager.GetString("license_failed_not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Your blood level is to low to be drawn.&quot;.
        /// </summary>
        public static string low_blood {
            get {
                return ResourceManager.GetString("low_blood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already wearing a mask.&quot;.
        /// </summary>
        public static string mask_equiped {
            get {
                return ResourceManager.GetString("mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t use private messages with staff members.&quot;.
        /// </summary>
        public static string mps_only_admin {
            get {
                return ResourceManager.GetString("mps_only_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0} got a negative result.&quot;.
        /// </summary>
        public static string negative_result {
            get {
                return ResourceManager.GetString("negative_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any accessory.&quot;.
        /// </summary>
        public static string no_accessory_bought {
            get {
                return ResourceManager.GetString("no_accessory_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any accessory.&quot;.
        /// </summary>
        public static string no_accessory_equiped {
            get {
                return ResourceManager.GetString("no_accessory_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There are no staff members online, try again in a while.&quot;.
        /// </summary>
        public static string no_admins_on_duty_atm {
            get {
                return ResourceManager.GetString("no_admins_on_duty_atm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any bag.&quot;.
        /// </summary>
        public static string no_bag_bought {
            get {
                return ResourceManager.GetString("no_bag_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any bag.&quot;.
        /// </summary>
        public static string no_bag_equiped {
            get {
                return ResourceManager.GetString("no_bag_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There are no blood units remaining.&quot;.
        /// </summary>
        public static string no_blood_left {
            get {
                return ResourceManager.GetString("no_blood_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You didn&apos;t select any character.&quot;.
        /// </summary>
        public static string no_character_selected {
            get {
                return ResourceManager.GetString("no_character_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There are no clothes in the wardrobe.&quot;.
        /// </summary>
        public static string no_clothes_in_wardrobe {
            get {
                return ResourceManager.GetString("no_clothes_in_wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any earrings.&quot;.
        /// </summary>
        public static string no_ear_bought {
            get {
                return ResourceManager.GetString("no_ear_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any earrings.&quot;.
        /// </summary>
        public static string no_ear_equiped {
            get {
                return ResourceManager.GetString("no_ear_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any fish to sell.&quot;.
        /// </summary>
        public static string no_fish_sellable {
            get {
                return ResourceManager.GetString("no_fish_sellable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have a fishing rod in your right hand.&quot;.
        /// </summary>
        public static string no_fishing_rod {
            get {
                return ResourceManager.GetString("no_fishing_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any glasses.&quot;.
        /// </summary>
        public static string no_glasses_bought {
            get {
                return ResourceManager.GetString("no_glasses_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any glasses.&quot;.
        /// </summary>
        public static string no_glasses_equiped {
            get {
                return ResourceManager.GetString("no_glasses_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any hat.&quot;.
        /// </summary>
        public static string no_hat_bought {
            get {
                return ResourceManager.GetString("no_hat_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any hat.&quot;.
        /// </summary>
        public static string no_hat_equiped {
            get {
                return ResourceManager.GetString("no_hat_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any item in your inventory.&quot;.
        /// </summary>
        public static string no_items_inventory {
            get {
                return ResourceManager.GetString("no_items_inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any item near.&quot;.
        /// </summary>
        public static string no_items_near {
            get {
                return ResourceManager.GetString("no_items_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle&apos;s trunk is empty.&quot;.
        /// </summary>
        public static string no_items_trunk {
            get {
                return ResourceManager.GetString("no_items_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t purchased any mask.&quot;.
        /// </summary>
        public static string no_mask_bought {
            get {
                return ResourceManager.GetString("no_mask_bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not wearing any mask.&quot;.
        /// </summary>
        public static string no_mask_equiped {
            get {
                return ResourceManager.GetString("no_mask_equiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s no police control saved.&quot;.
        /// </summary>
        public static string no_police_controls {
            get {
                return ResourceManager.GetString("no_police_controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Nobody offered you to repaint your vehicle.&quot;.
        /// </summary>
        public static string no_repaint_offered {
            get {
                return ResourceManager.GetString("no_repaint_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Nobody offered you a repairment.&quot;.
        /// </summary>
        public static string no_repair_offered {
            get {
                return ResourceManager.GetString("no_repair_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Nobody offered you a sexual service.&quot;.
        /// </summary>
        public static string no_service_offered {
            get {
                return ResourceManager.GetString("no_service_offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Nobody is driving this taxi.&quot;.
        /// </summary>
        public static string no_taxi_driver {
            get {
                return ResourceManager.GetString("no_taxi_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any phone in your hand.&quot;.
        /// </summary>
        public static string no_telephone_hand {
            get {
                return ResourceManager.GetString("no_telephone_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any vehicle near you.&quot;.
        /// </summary>
        public static string no_vehicles_near {
            get {
                return ResourceManager.GetString("no_vehicles_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any relay equipment in your hand.&quot;.
        /// </summary>
        public static string no_walkie_in_hand {
            get {
                return ResourceManager.GetString("no_walkie_in_hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have this vehicle&apos;s keys.&quot;.
        /// </summary>
        public static string not_car_keys {
            get {
                return ResourceManager.GetString("not_car_keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You didn&apos;t take any order.&quot;.
        /// </summary>
        public static string not_delivering_order {
            get {
                return ResourceManager.GetString("not_delivering_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not fastfood deliverer.&quot;.
        /// </summary>
        public static string not_fastfood {
            get {
                return ResourceManager.GetString("not_fastfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle isn&apos;t a fishing boat.&quot;.
        /// </summary>
        public static string not_fishing_boat {
            get {
                return ResourceManager.GetString("not_fishing_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in a fishing store.&quot;.
        /// </summary>
        public static string not_fishing_business {
            get {
                return ResourceManager.GetString("not_fishing_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in a fishing area.&quot;.
        /// </summary>
        public static string not_fishing_zone {
            get {
                return ResourceManager.GetString("not_fishing_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any gas station.&quot;.
        /// </summary>
        public static string not_fuel_station_near {
            get {
                return ResourceManager.GetString("not_fuel_station_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any garbage bag near.&quot;.
        /// </summary>
        public static string not_garbage_near {
            get {
                return ResourceManager.GetString("not_garbage_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not a hooker.&quot;.
        /// </summary>
        public static string not_hooker {
            get {
                return ResourceManager.GetString("not_hooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the door of any house or business.&quot;.
        /// </summary>
        public static string not_house_business {
            get {
                return ResourceManager.GetString("not_house_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s no house near you.&quot;.
        /// </summary>
        public static string not_house_near {
            get {
                return ResourceManager.GetString("not_house_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not doing the car practical exam.&quot;.
        /// </summary>
        public static string not_in_car_practice {
            get {
                return ResourceManager.GetString("not_in_car_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any cat dealer.&quot;.
        /// </summary>
        public static string not_in_carshop {
            get {
                return ResourceManager.GetString("not_in_carshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any workshop.&quot;.
        /// </summary>
        public static string not_in_mechanic_workshop {
            get {
                return ResourceManager.GetString("not_in_mechanic_workshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in a pawn shop.&quot;.
        /// </summary>
        public static string not_in_pawn_show {
            get {
                return ResourceManager.GetString("not_in_pawn_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any job route.&quot;.
        /// </summary>
        public static string not_in_route {
            get {
                return ResourceManager.GetString("not_in_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t inside any vehicle.&quot;.
        /// </summary>
        public static string not_in_vehicle {
            get {
                return ResourceManager.GetString("not_in_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the same faction this vehicle is.&quot;.
        /// </summary>
        public static string not_in_vehicle_faction {
            get {
                return ResourceManager.GetString("not_in_vehicle_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required job to drive this vehicle.&quot;.
        /// </summary>
        public static string not_in_vehicle_job {
            get {
                return ResourceManager.GetString("not_in_vehicle_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You must be into a vehicle.&quot;.
        /// </summary>
        public static string not_in_vehicle_type_car {
            get {
                return ResourceManager.GetString("not_in_vehicle_type_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player isn&apos;t being interviewed.&quot;.
        /// </summary>
        public static string not_on_air {
            get {
                return ResourceManager.GetString("not_on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t own any radio channel.&quot;.
        /// </summary>
        public static string not_owned_channel {
            get {
                return ResourceManager.GetString("not_owned_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t park your vehicle here.&quot;.
        /// </summary>
        public static string not_parking_allowed {
            get {
                return ResourceManager.GetString("not_parking_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any parking.&quot;.
        /// </summary>
        public static string not_parking_near {
            get {
                return ResourceManager.GetString("not_parking_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in a phone call.&quot;.
        /// </summary>
        public static string not_phone_talking {
            get {
                return ResourceManager.GetString("not_phone_talking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not the chief from the police department.&quot;.
        /// </summary>
        public static string not_police_chief {
            get {
                return ResourceManager.GetString("not_police_chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0} products in order to do that.&quot;.
        /// </summary>
        public static string not_required_products {
            get {
                return ResourceManager.GetString("not_required_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the scrapyard.&quot;.
        /// </summary>
        public static string not_scrapyard_near {
            get {
                return ResourceManager.GetString("not_scrapyard_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in duty.&quot;.
        /// </summary>
        public static string not_service {
            get {
                return ResourceManager.GetString("not_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not spectating any player.&quot;.
        /// </summary>
        public static string not_spectating {
            get {
                return ResourceManager.GetString("not_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not allowed to test this vehicle.&quot;.
        /// </summary>
        public static string not_testing_vehicle {
            get {
                return ResourceManager.GetString("not_testing_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not a thief.&quot;.
        /// </summary>
        public static string not_thief {
            get {
                return ResourceManager.GetString("not_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any workshop and don&apos;t have any towtruck near.&quot;.
        /// </summary>
        public static string not_valid_repair_place {
            get {
                return ResourceManager.GetString("not_valid_repair_place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not driving the vehicle.&quot;.
        /// </summary>
        public static string not_vehicle_driving {
            get {
                return ResourceManager.GetString("not_vehicle_driving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t on passenger&apos;s seat.&quot;.
        /// </summary>
        public static string not_vehicle_passenger {
            get {
                return ResourceManager.GetString("not_vehicle_passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This is not your job vehicle.&quot;.
        /// </summary>
        public static string not_your_job_vehicle {
            get {
                return ResourceManager.GetString("not_your_job_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is being interviewed already.&quot;.
        /// </summary>
        public static string on_air {
            get {
                return ResourceManager.GetString("on_air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already delivering an order.&quot;.
        /// </summary>
        public static string order_delivering {
            get {
                return ResourceManager.GetString("order_delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s no order in the list to attend.&quot;.
        /// </summary>
        public static string order_none {
            get {
                return ResourceManager.GetString("order_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This order has already been attended.&quot;.
        /// </summary>
        public static string order_taken {
            get {
                return ResourceManager.GetString("order_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The client has tired of waiting his order.&quot;.
        /// </summary>
        public static string order_timeout {
            get {
                return ResourceManager.GetString("order_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This parking is full.&quot;.
        /// </summary>
        public static string parking_full {
            get {
                return ResourceManager.GetString("parking_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t only link a house to a garage.&quot;.
        /// </summary>
        public static string parking_not_garage {
            get {
                return ResourceManager.GetString("parking_not_garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to get your car from the parking.&quot;.
        /// </summary>
        public static string parking_not_money {
            get {
                return ResourceManager.GetString("parking_not_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is already in a faction.&quot;.
        /// </summary>
        public static string player_already_faction {
            get {
                return ResourceManager.GetString("player_already_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already fishing.&quot;.
        /// </summary>
        public static string player_already_fishing {
            get {
                return ResourceManager.GetString("player_already_fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already hotwiring a vehicle.&quot;.
        /// </summary>
        public static string player_already_hotwiring {
            get {
                return ResourceManager.GetString("player_already_hotwiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player already has a job.&quot;.
        /// </summary>
        public static string player_already_job {
            get {
                return ResourceManager.GetString("player_already_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Your license is still valid.&quot;.
        /// </summary>
        public static string player_already_license {
            get {
                return ResourceManager.GetString("player_already_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already stealing items.&quot;.
        /// </summary>
        public static string player_already_stealing {
            get {
                return ResourceManager.GetString("player_already_stealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t use the chat in the lobby.&quot;.
        /// </summary>
        public static string player_cant_chat {
            get {
                return ResourceManager.GetString("player_cant_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t use any command in the lobby.&quot;.
        /// </summary>
        public static string player_cant_command {
            get {
                return ResourceManager.GetString("player_cant_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t hotwire your own vehicle.&quot;.
        /// </summary>
        public static string player_cant_hotwire_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_hotwire_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t lockpick your own vehicle.&quot;.
        /// </summary>
        public static string player_cant_lockpick_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_lockpick_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s nothing to steal near here.&quot;.
        /// </summary>
        public static string player_cant_rob {
            get {
                return ResourceManager.GetString("player_cant_rob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t break into your own house.&quot;.
        /// </summary>
        public static string player_cant_rob_own_house {
            get {
                return ResourceManager.GetString("player_cant_rob_own_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t steal into your own vehicle.&quot;.
        /// </summary>
        public static string player_cant_rob_own_vehicle {
            get {
                return ResourceManager.GetString("player_cant_rob_own_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t be the target player.&quot;.
        /// </summary>
        public static string player_cant_self {
            get {
                return ResourceManager.GetString("player_cant_self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re still nervous from your last robbery, you&apos;ll have to wait 1 hour.&quot;.
        /// </summary>
        public static string player_cooldown_thief {
            get {
                return ResourceManager.GetString("player_cooldown_thief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t fine yourself.&quot;.
        /// </summary>
        public static string player_fined_himself {
            get {
                return ResourceManager.GetString("player_fined_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t handcuff yourself.&quot;.
        /// </summary>
        public static string player_handcuffed_himself {
            get {
                return ResourceManager.GetString("player_handcuffed_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have you identification card.&quot;.
        /// </summary>
        public static string player_has_identification {
            get {
                return ResourceManager.GetString("player_has_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a job.&quot;.
        /// </summary>
        public static string player_has_job {
            get {
                return ResourceManager.GetString("player_has_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a medical insurance.&quot;.
        /// </summary>
        public static string player_has_medical_insurance {
            get {
                return ResourceManager.GetString("player_has_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a taxi license.&quot;.
        /// </summary>
        public static string player_has_taxi_license {
            get {
                return ResourceManager.GetString("player_has_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already attending a report.&quot;.
        /// </summary>
        public static string player_have_faction_warning {
            get {
                return ResourceManager.GetString("player_have_faction_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a house rented.&quot;.
        /// </summary>
        public static string player_house_rented {
            get {
                return ResourceManager.GetString("player_house_rented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t incriminate yourself.&quot;.
        /// </summary>
        public static string player_incriminated_himself {
            get {
                return ResourceManager.GetString("player_incriminated_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t do this inside a vehicle.&quot;.
        /// </summary>
        public static string player_inside_vehicle {
            get {
                return ResourceManager.GetString("player_inside_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t do that while dead.&quot;.
        /// </summary>
        public static string player_is_dead {
            get {
                return ResourceManager.GetString("player_is_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You haven&apos;t spent the required time in your current job.&quot;.
        /// </summary>
        public static string player_job_restriction {
            get {
                return ResourceManager.GetString("player_job_restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can apply for this job being part of a state faction.&quot;.
        /// </summary>
        public static string player_job_state_faction {
            get {
                return ResourceManager.GetString("player_job_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Player can&apos;t have more lent vehicles.&quot;.
        /// </summary>
        public static string player_keys_full {
            get {
                return ResourceManager.GetString("player_keys_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have nothing to use as a bait.&quot;.
        /// </summary>
        public static string player_no_baits {
            get {
                return ResourceManager.GetString("player_no_baits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in any faction.&quot;.
        /// </summary>
        public static string player_no_faction {
            get {
                return ResourceManager.GetString("player_no_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You didn&apos;t select any fine to pay.&quot;.
        /// </summary>
        public static string player_no_fines {
            get {
                return ResourceManager.GetString("player_no_fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any jerrycan in your hand.&quot;.
        /// </summary>
        public static string player_no_jerrycan {
            get {
                return ResourceManager.GetString("player_no_jerrycan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any job.&quot;.
        /// </summary>
        public static string player_no_job {
            get {
                return ResourceManager.GetString("player_no_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not the owner of this business.&quot;.
        /// </summary>
        public static string player_not_business_owner {
            get {
                return ResourceManager.GetString("player_not_business_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Nobody&apos;s calling at you in this moment.&quot;.
        /// </summary>
        public static string player_not_called {
            get {
                return ResourceManager.GetString("player_not_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have to be in a car to use this animation.&quot;.
        /// </summary>
        public static string player_not_car {
            get {
                return ResourceManager.GetString("player_not_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is not dead.&quot;.
        /// </summary>
        public static string player_not_dead {
            get {
                return ResourceManager.GetString("player_not_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the driving school.&quot;.
        /// </summary>
        public static string player_not_driving_school {
            get {
                return ResourceManager.GetString("player_not_driving_school", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t part of the emergency department.&quot;.
        /// </summary>
        public static string player_not_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have enough money.&quot;.
        /// </summary>
        public static string player_not_enough_money {
            get {
                return ResourceManager.GetString("player_not_enough_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required rank to get ammunition neither weapons.&quot;.
        /// </summary>
        public static string player_not_enough_police_rank {
            get {
                return ResourceManager.GetString("player_not_enough_police_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to pay your fines.&quot;.
        /// </summary>
        public static string player_not_fine_money {
            get {
                return ResourceManager.GetString("player_not_fine_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not fisherman.&quot;.
        /// </summary>
        public static string player_not_fisherman {
            get {
                return ResourceManager.GetString("player_not_fisherman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is not connected to the server.&quot;.
        /// </summary>
        public static string player_not_found {
            get {
                return ResourceManager.GetString("player_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have this garage&apos;s keys.&quot;.
        /// </summary>
        public static string player_not_garage_access {
            get {
                return ResourceManager.GetString("player_not_garage_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not a garbage man.&quot;.
        /// </summary>
        public static string player_not_garbage {
            get {
                return ResourceManager.GetString("player_not_garbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not the owner of this house.&quot;.
        /// </summary>
        public static string player_not_house_owner {
            get {
                return ResourceManager.GetString("player_not_house_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is not wounded.&quot;.
        /// </summary>
        public static string player_not_hurt {
            get {
                return ResourceManager.GetString("player_not_hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to get your identification card.&quot;.
        /// </summary>
        public static string player_not_identification_money {
            get {
                return ResourceManager.GetString("player_not_identification_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not inside any house.&quot;.
        /// </summary>
        public static string player_not_in_house {
            get {
                return ResourceManager.GetString("player_not_in_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have to be in the left rear seat of the news van.&quot;.
        /// </summary>
        public static string player_not_in_news_van {
            get {
                return ResourceManager.GetString("player_not_in_news_van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You have to be on the back right rear seat of the van.&quot;.
        /// </summary>
        public static string player_not_in_right_rear {
            get {
                return ResourceManager.GetString("player_not_in_right_rear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the police station&apos;s lockers.&quot;.
        /// </summary>
        public static string player_not_in_room_lockers {
            get {
                return ResourceManager.GetString("player_not_in_room_lockers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player isn&apos;t in your faction.&quot;.
        /// </summary>
        public static string player_not_in_same_faction {
            get {
                return ResourceManager.GetString("player_not_in_same_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in jail&apos;s entrance.&quot;.
        /// </summary>
        public static string player_not_jail_area {
            get {
                return ResourceManager.GetString("player_not_jail_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not mechanic.&quot;.
        /// </summary>
        public static string player_not_mechanic {
            get {
                return ResourceManager.GetString("player_not_mechanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have a medical insurance.&quot;.
        /// </summary>
        public static string player_not_medical_insurance {
            get {
                return ResourceManager.GetString("player_not_medical_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to get a medical insurance.&quot;.
        /// </summary>
        public static string player_not_medical_insurance_money {
            get {
                return ResourceManager.GetString("player_not_medical_insurance_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t a journalist.&quot;.
        /// </summary>
        public static string player_not_news_faction {
            get {
                return ResourceManager.GetString("player_not_news_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t on duty as staff.&quot;.
        /// </summary>
        public static string player_not_on_admin_duty {
            get {
                return ResourceManager.GetString("player_not_on_admin_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t on duty.&quot;.
        /// </summary>
        public static string player_not_on_duty {
            get {
                return ResourceManager.GetString("player_not_on_duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t part of the police department neither emergency department.&quot;.
        /// </summary>
        public static string player_not_police_emergency_faction {
            get {
                return ResourceManager.GetString("player_not_police_emergency_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t part of the police department.&quot;.
        /// </summary>
        public static string player_not_police_faction {
            get {
                return ResourceManager.GetString("player_not_police_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required money to pay the rental fee.&quot;.
        /// </summary>
        public static string player_not_rent_money {
            get {
                return ResourceManager.GetString("player_not_rent_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any fishing rod and you&apos;re not in any fishing boat.&quot;.
        /// </summary>
        public static string player_not_rod_boat {
            get {
                return ResourceManager.GetString("player_not_rod_boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You aren&apos;t part of any state faction.&quot;.
        /// </summary>
        public static string player_not_state_faction {
            get {
                return ResourceManager.GetString("player_not_state_faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any stolen item.&quot;.
        /// </summary>
        public static string player_not_stolen_items {
            get {
                return ResourceManager.GetString("player_not_stolen_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t own any taxi driving license.&quot;.
        /// </summary>
        public static string player_not_taxi_license {
            get {
                return ResourceManager.GetString("player_not_taxi_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You need {0}$ to get the taxi license.&quot;.
        /// </summary>
        public static string player_not_taxi_license_money {
            get {
                return ResourceManager.GetString("player_not_taxi_license_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the center of the city.&quot;.
        /// </summary>
        public static string player_not_thief_area {
            get {
                return ResourceManager.GetString("player_not_thief_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not in the town hall.&quot;.
        /// </summary>
        public static string player_not_townhall {
            get {
                return ResourceManager.GetString("player_not_townhall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don-t have this vehicle&apos;s keys.&quot;.
        /// </summary>
        public static string player_not_veh_owner {
            get {
                return ResourceManager.GetString("player_not_veh_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re already refueling your vehicle.&quot;.
        /// </summary>
        public static string player_refueling {
            get {
                return ResourceManager.GetString("player_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t frisk yourself.&quot;.
        /// </summary>
        public static string player_searched_himself {
            get {
                return ResourceManager.GetString("player_searched_himself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player is spectating another player.&quot;.
        /// </summary>
        public static string player_spectating {
            get {
                return ResourceManager.GetString("player_spectating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You left the vehicle and stopped hotwiring it.&quot;.
        /// </summary>
        public static string player_stopped_hotwire {
            get {
                return ResourceManager.GetString("player_stopped_hotwire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re too far away from the target player.&quot;.
        /// </summary>
        public static string player_too_far {
            get {
                return ResourceManager.GetString("player_too_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t own any identification card, remember that it&apos;s mandatory to be identified.&quot;.
        /// </summary>
        public static string player_undocumented {
            get {
                return ResourceManager.GetString("player_undocumented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Price must be greater than 0$.&quot;.
        /// </summary>
        public static string price_positive {
            get {
                return ResourceManager.GetString("price_positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You&apos;re not connected to any radio frequency.&quot;.
        /// </summary>
        public static string radio_frequency_none {
            get {
                return ResourceManager.GetString("radio_frequency_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required rank to dismiss members.&quot;.
        /// </summary>
        public static string rank_too_low_dismiss {
            get {
                return ResourceManager.GetString("rank_too_low_dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required rank to change members&apos; rank.&quot;.
        /// </summary>
        public static string rank_too_low_rank {
            get {
                return ResourceManager.GetString("rank_too_low_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have the required rank to recruit new members.&quot;.
        /// </summary>
        public static string rank_too_low_recruit {
            get {
                return ResourceManager.GetString("rank_too_low_recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You don&apos;t have any item in your right hand.&quot;.
        /// </summary>
        public static string right_hand_empty {
            get {
                return ResourceManager.GetString("right_hand_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have an item in your right hand.&quot;.
        /// </summary>
        public static string right_hand_occupied {
            get {
                return ResourceManager.GetString("right_hand_occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t leave while you&apos;re stealing items.&quot;.
        /// </summary>
        public static string stealing_progress {
            get {
                return ResourceManager.GetString("stealing_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The target player has already an item in his right hand.&quot;.
        /// </summary>
        public static string target_right_hand_not_empty {
            get {
                return ResourceManager.GetString("target_right_hand_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You already have a tattoo like this one.&quot;.
        /// </summary>
        public static string tattoo_duplicated {
            get {
                return ResourceManager.GetString("tattoo_duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The taxi driver already has a destination point.&quot;.
        /// </summary>
        public static string taxi_has_path {
            get {
                return ResourceManager.GetString("taxi_has_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t transfer money to your own account.&quot;.
        /// </summary>
        public static string transfer_money_own {
            get {
                return ResourceManager.GetString("transfer_money_own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle is already unlocked.&quot;.
        /// </summary>
        public static string veh_already_unlocked {
            get {
                return ResourceManager.GetString("veh_already_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle isn&apos;t drivable with your license.&quot;.
        /// </summary>
        public static string vehicle_driving_not_suitable {
            get {
                return ResourceManager.GetString("vehicle_driving_not_suitable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t park this vehicle.&quot;.
        /// </summary>
        public static string vehicle_faction_park {
            get {
                return ResourceManager.GetString("vehicle_faction_park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Couldn&apos;t find any vehicle with that identifier.&quot;.
        /// </summary>
        public static string vehicle_not_exists {
            get {
                return ResourceManager.GetString("vehicle_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle can&apos;t be locked.&quot;.
        /// </summary>
        public static string vehicle_not_lockable {
            get {
                return ResourceManager.GetString("vehicle_not_lockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;This vehicle doesn&apos;t have any megaphone installed.&quot;.
        /// </summary>
        public static string vehicle_not_megaphone {
            get {
                return ResourceManager.GetString("vehicle_not_megaphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The vehicle is not parked here.&quot;.
        /// </summary>
        public static string vehicle_not_this_parking {
            get {
                return ResourceManager.GetString("vehicle_not_this_parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The vehicle is being refueled.&quot;.
        /// </summary>
        public static string vehicle_refueling {
            get {
                return ResourceManager.GetString("vehicle_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t turn the engine on while the vehicle is being refueled.&quot;.
        /// </summary>
        public static string vehicle_start_refueling {
            get {
                return ResourceManager.GetString("vehicle_start_refueling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;You can&apos;t turn the engine on while they&apos;re unpacking the weapons.&quot;.
        /// </summary>
        public static string vehicle_start_weapon_unpacking {
            get {
                return ResourceManager.GetString("vehicle_start_weapon_unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The vehicle&apos;s trunk is already closed.&quot;.
        /// </summary>
        public static string vehicle_trunk_closed {
            get {
                return ResourceManager.GetString("vehicle_trunk_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s already somebody interacting with this vehicle&apos;s trunk.&quot;.
        /// </summary>
        public static string vehicle_trunk_in_use {
            get {
                return ResourceManager.GetString("vehicle_trunk_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The vehicle&apos;s trunk is already opened.&quot;.
        /// </summary>
        public static string vehicle_trunk_opened {
            get {
                return ResourceManager.GetString("vehicle_trunk_opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The vehicle is too far away from you.&quot;.
        /// </summary>
        public static string wanted_vehicle_far {
            get {
                return ResourceManager.GetString("wanted_vehicle_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;The weapons event has already started.&quot;.
        /// </summary>
        public static string weapon_event_on_course {
            get {
                return ResourceManager.GetString("weapon_event_on_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Your weapon license has expired.&quot;.
        /// </summary>
        public static string weapon_license_expired {
            get {
                return ResourceManager.GetString("weapon_license_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;Weather value must be in 0 to 12 interval.&quot;.
        /// </summary>
        public static string weather_value_invalid {
            get {
                return ResourceManager.GetString("weather_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;There&apos;s no need to repair this wheel.&quot;.
        /// </summary>
        public static string wheel_not_popped {
            get {
                return ResourceManager.GetString("wheel_not_popped", resourceCulture);
            }
        }
    }
}
